-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (lin64) Build 6299465 Fri Nov 14 12:34:56 MST 2025
-- Date        : Mon Jul 27 16:08:49 2026
-- Host        : Mariana running 64-bit Ubuntu 22.04.5 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_snn_top_hls_0_0_stub.vhdl
-- Design      : design_1_snn_top_hls_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_ctrl_ARADDR : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s_axi_ctrl_ARREADY : out STD_LOGIC;
    s_axi_ctrl_ARVALID : in STD_LOGIC;
    s_axi_ctrl_AWADDR : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s_axi_ctrl_AWREADY : out STD_LOGIC;
    s_axi_ctrl_AWVALID : in STD_LOGIC;
    s_axi_ctrl_BREADY : in STD_LOGIC;
    s_axi_ctrl_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_ctrl_BVALID : out STD_LOGIC;
    s_axi_ctrl_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_ctrl_RREADY : in STD_LOGIC;
    s_axi_ctrl_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_ctrl_RVALID : out STD_LOGIC;
    s_axi_ctrl_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_ctrl_WREADY : out STD_LOGIC;
    s_axi_ctrl_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_ctrl_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    s_axis_spikes_TDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_spikes_TDEST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_spikes_TID : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_spikes_TKEEP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_spikes_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_spikes_TREADY : out STD_LOGIC;
    s_axis_spikes_TSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_spikes_TUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_spikes_TVALID : in STD_LOGIC;
    s_axis_data_TDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_data_TDEST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_data_TID : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_data_TKEEP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_data_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_data_TREADY : out STD_LOGIC;
    s_axis_data_TSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_data_TUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_data_TVALID : in STD_LOGIC;
    s_axis_weights_TDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_weights_TDEST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_weights_TID : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_weights_TKEEP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_weights_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_weights_TREADY : out STD_LOGIC;
    s_axis_weights_TSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_weights_TUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_weights_TVALID : in STD_LOGIC;
    m_axis_spikes_TDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axis_spikes_TDEST : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_spikes_TID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_spikes_TKEEP : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_spikes_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_spikes_TREADY : in STD_LOGIC;
    m_axis_spikes_TSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_spikes_TUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_spikes_TVALID : out STD_LOGIC;
    m_axis_weights_TDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axis_weights_TDEST : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_weights_TID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_weights_TKEEP : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_weights_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_weights_TREADY : in STD_LOGIC;
    m_axis_weights_TSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_weights_TUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_weights_TVALID : out STD_LOGIC;
    spike_in_valid : out STD_LOGIC_VECTOR ( 0 to 0 );
    spike_in_neuron_id : out STD_LOGIC_VECTOR ( 10 downto 0 );
    spike_in_weight : out STD_LOGIC_VECTOR ( 7 downto 0 );
    spike_in_ready : in STD_LOGIC_VECTOR ( 0 to 0 );
    spike_out_valid : in STD_LOGIC_VECTOR ( 0 to 0 );
    spike_out_neuron_id : in STD_LOGIC_VECTOR ( 10 downto 0 );
    spike_out_weight : in STD_LOGIC_VECTOR ( 7 downto 0 );
    spike_out_ready : out STD_LOGIC_VECTOR ( 0 to 0 );
    learn_weight_valid : out STD_LOGIC_VECTOR ( 0 to 0 );
    learn_weight_group : out STD_LOGIC_VECTOR ( 3 downto 0 );
    learn_weight_src : out STD_LOGIC_VECTOR ( 6 downto 0 );
    learn_weight_dst : out STD_LOGIC_VECTOR ( 6 downto 0 );
    learn_weight_data : out STD_LOGIC_VECTOR ( 7 downto 0 );
    learn_weight_exc : out STD_LOGIC_VECTOR ( 0 to 0 );
    learn_weight_is_inter : out STD_LOGIC_VECTOR ( 0 to 0 );
    learn_weight_dst_group : out STD_LOGIC_VECTOR ( 3 downto 0 );
    learn_weight_fanout_idx : out STD_LOGIC_VECTOR ( 3 downto 0 );
    learn_weight_ready : in STD_LOGIC_VECTOR ( 0 to 0 );
    snn_enable : out STD_LOGIC_VECTOR ( 0 to 0 );
    snn_reset : out STD_LOGIC_VECTOR ( 0 to 0 );
    threshold_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    leak_rate_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    snn_ready : in STD_LOGIC_VECTOR ( 0 to 0 );
    snn_busy : in STD_LOGIC_VECTOR ( 0 to 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_snn_top_hls_0_0,snn_top_hls,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_snn_top_hls_0_0,snn_top_hls,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=snn_top_hls,x_ipVersion=1.0,x_ipCoreRevision=2114715166,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CTRL_ADDR_WIDTH=8,C_S_AXI_CTRL_DATA_WIDTH=32}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_ctrl_ARADDR[7:0],s_axi_ctrl_ARREADY,s_axi_ctrl_ARVALID,s_axi_ctrl_AWADDR[7:0],s_axi_ctrl_AWREADY,s_axi_ctrl_AWVALID,s_axi_ctrl_BREADY,s_axi_ctrl_BRESP[1:0],s_axi_ctrl_BVALID,s_axi_ctrl_RDATA[31:0],s_axi_ctrl_RREADY,s_axi_ctrl_RRESP[1:0],s_axi_ctrl_RVALID,s_axi_ctrl_WDATA[31:0],s_axi_ctrl_WREADY,s_axi_ctrl_WSTRB[3:0],s_axi_ctrl_WVALID,ap_clk,ap_rst_n,interrupt,s_axis_spikes_TDATA[31:0],s_axis_spikes_TDEST[0:0],s_axis_spikes_TID[0:0],s_axis_spikes_TKEEP[3:0],s_axis_spikes_TLAST[0:0],s_axis_spikes_TREADY,s_axis_spikes_TSTRB[3:0],s_axis_spikes_TUSER[0:0],s_axis_spikes_TVALID,s_axis_data_TDATA[31:0],s_axis_data_TDEST[0:0],s_axis_data_TID[0:0],s_axis_data_TKEEP[3:0],s_axis_data_TLAST[0:0],s_axis_data_TREADY,s_axis_data_TSTRB[3:0],s_axis_data_TUSER[0:0],s_axis_data_TVALID,s_axis_weights_TDATA[31:0],s_axis_weights_TDEST[0:0],s_axis_weights_TID[0:0],s_axis_weights_TKEEP[3:0],s_axis_weights_TLAST[0:0],s_axis_weights_TREADY,s_axis_weights_TSTRB[3:0],s_axis_weights_TUSER[0:0],s_axis_weights_TVALID,m_axis_spikes_TDATA[31:0],m_axis_spikes_TDEST[0:0],m_axis_spikes_TID[0:0],m_axis_spikes_TKEEP[3:0],m_axis_spikes_TLAST[0:0],m_axis_spikes_TREADY,m_axis_spikes_TSTRB[3:0],m_axis_spikes_TUSER[0:0],m_axis_spikes_TVALID,m_axis_weights_TDATA[31:0],m_axis_weights_TDEST[0:0],m_axis_weights_TID[0:0],m_axis_weights_TKEEP[3:0],m_axis_weights_TLAST[0:0],m_axis_weights_TREADY,m_axis_weights_TSTRB[3:0],m_axis_weights_TUSER[0:0],m_axis_weights_TVALID,spike_in_valid[0:0],spike_in_neuron_id[10:0],spike_in_weight[7:0],spike_in_ready[0:0],spike_out_valid[0:0],spike_out_neuron_id[10:0],spike_out_weight[7:0],spike_out_ready[0:0],learn_weight_valid[0:0],learn_weight_group[3:0],learn_weight_src[6:0],learn_weight_dst[6:0],learn_weight_data[7:0],learn_weight_exc[0:0],learn_weight_is_inter[0:0],learn_weight_dst_group[3:0],learn_weight_fanout_idx[3:0],learn_weight_ready[0:0],snn_enable[0:0],snn_reset[0:0],threshold_out[15:0],leak_rate_out[15:0],snn_ready[0:0],snn_busy[0:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_ctrl_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_ctrl_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_ctrl_ARADDR : signal is "XIL_INTERFACENAME s_axi_ctrl, ADDR_WIDTH 8, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_ctrl_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl ARREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl ARVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl AWADDR";
  attribute X_INTERFACE_INFO of s_axi_ctrl_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl AWREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl AWVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl BREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl BRESP";
  attribute X_INTERFACE_INFO of s_axi_ctrl_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl BVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RDATA";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RRESP";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WDATA";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WSTRB";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_ctrl:s_axis_spikes:s_axis_data:s_axis_weights:m_axis_spikes:m_axis_weights, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of s_axis_spikes_TDATA : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TDATA";
  attribute X_INTERFACE_MODE of s_axis_spikes_TDATA : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_spikes_TDATA : signal is "XIL_INTERFACENAME s_axis_spikes, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_spikes_TDEST : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TDEST";
  attribute X_INTERFACE_INFO of s_axis_spikes_TID : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TID";
  attribute X_INTERFACE_INFO of s_axis_spikes_TKEEP : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TKEEP";
  attribute X_INTERFACE_INFO of s_axis_spikes_TLAST : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TLAST";
  attribute X_INTERFACE_INFO of s_axis_spikes_TREADY : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TREADY";
  attribute X_INTERFACE_INFO of s_axis_spikes_TSTRB : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TSTRB";
  attribute X_INTERFACE_INFO of s_axis_spikes_TUSER : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TUSER";
  attribute X_INTERFACE_INFO of s_axis_spikes_TVALID : signal is "xilinx.com:interface:axis:1.0 s_axis_spikes TVALID";
  attribute X_INTERFACE_INFO of s_axis_data_TDATA : signal is "xilinx.com:interface:axis:1.0 s_axis_data TDATA";
  attribute X_INTERFACE_MODE of s_axis_data_TDATA : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_data_TDATA : signal is "XIL_INTERFACENAME s_axis_data, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_data_TDEST : signal is "xilinx.com:interface:axis:1.0 s_axis_data TDEST";
  attribute X_INTERFACE_INFO of s_axis_data_TID : signal is "xilinx.com:interface:axis:1.0 s_axis_data TID";
  attribute X_INTERFACE_INFO of s_axis_data_TKEEP : signal is "xilinx.com:interface:axis:1.0 s_axis_data TKEEP";
  attribute X_INTERFACE_INFO of s_axis_data_TLAST : signal is "xilinx.com:interface:axis:1.0 s_axis_data TLAST";
  attribute X_INTERFACE_INFO of s_axis_data_TREADY : signal is "xilinx.com:interface:axis:1.0 s_axis_data TREADY";
  attribute X_INTERFACE_INFO of s_axis_data_TSTRB : signal is "xilinx.com:interface:axis:1.0 s_axis_data TSTRB";
  attribute X_INTERFACE_INFO of s_axis_data_TUSER : signal is "xilinx.com:interface:axis:1.0 s_axis_data TUSER";
  attribute X_INTERFACE_INFO of s_axis_data_TVALID : signal is "xilinx.com:interface:axis:1.0 s_axis_data TVALID";
  attribute X_INTERFACE_INFO of s_axis_weights_TDATA : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TDATA";
  attribute X_INTERFACE_MODE of s_axis_weights_TDATA : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_weights_TDATA : signal is "XIL_INTERFACENAME s_axis_weights, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_weights_TDEST : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TDEST";
  attribute X_INTERFACE_INFO of s_axis_weights_TID : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TID";
  attribute X_INTERFACE_INFO of s_axis_weights_TKEEP : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TKEEP";
  attribute X_INTERFACE_INFO of s_axis_weights_TLAST : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TLAST";
  attribute X_INTERFACE_INFO of s_axis_weights_TREADY : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TREADY";
  attribute X_INTERFACE_INFO of s_axis_weights_TSTRB : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TSTRB";
  attribute X_INTERFACE_INFO of s_axis_weights_TUSER : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TUSER";
  attribute X_INTERFACE_INFO of s_axis_weights_TVALID : signal is "xilinx.com:interface:axis:1.0 s_axis_weights TVALID";
  attribute X_INTERFACE_INFO of m_axis_spikes_TDATA : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TDATA";
  attribute X_INTERFACE_MODE of m_axis_spikes_TDATA : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_spikes_TDATA : signal is "XIL_INTERFACENAME m_axis_spikes, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_spikes_TDEST : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TDEST";
  attribute X_INTERFACE_INFO of m_axis_spikes_TID : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TID";
  attribute X_INTERFACE_INFO of m_axis_spikes_TKEEP : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TKEEP";
  attribute X_INTERFACE_INFO of m_axis_spikes_TLAST : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TLAST";
  attribute X_INTERFACE_INFO of m_axis_spikes_TREADY : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TREADY";
  attribute X_INTERFACE_INFO of m_axis_spikes_TSTRB : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TSTRB";
  attribute X_INTERFACE_INFO of m_axis_spikes_TUSER : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TUSER";
  attribute X_INTERFACE_INFO of m_axis_spikes_TVALID : signal is "xilinx.com:interface:axis:1.0 m_axis_spikes TVALID";
  attribute X_INTERFACE_INFO of m_axis_weights_TDATA : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TDATA";
  attribute X_INTERFACE_MODE of m_axis_weights_TDATA : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_weights_TDATA : signal is "XIL_INTERFACENAME m_axis_weights, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_weights_TDEST : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TDEST";
  attribute X_INTERFACE_INFO of m_axis_weights_TID : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TID";
  attribute X_INTERFACE_INFO of m_axis_weights_TKEEP : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TKEEP";
  attribute X_INTERFACE_INFO of m_axis_weights_TLAST : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TLAST";
  attribute X_INTERFACE_INFO of m_axis_weights_TREADY : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TREADY";
  attribute X_INTERFACE_INFO of m_axis_weights_TSTRB : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TSTRB";
  attribute X_INTERFACE_INFO of m_axis_weights_TUSER : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TUSER";
  attribute X_INTERFACE_INFO of m_axis_weights_TVALID : signal is "xilinx.com:interface:axis:1.0 m_axis_weights TVALID";
  attribute X_INTERFACE_INFO of spike_in_valid : signal is "xilinx.com:signal:data:1.0 spike_in_valid DATA";
  attribute X_INTERFACE_MODE of spike_in_valid : signal is "master";
  attribute X_INTERFACE_PARAMETER of spike_in_valid : signal is "XIL_INTERFACENAME spike_in_valid, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_in_neuron_id : signal is "xilinx.com:signal:data:1.0 spike_in_neuron_id DATA";
  attribute X_INTERFACE_MODE of spike_in_neuron_id : signal is "master";
  attribute X_INTERFACE_PARAMETER of spike_in_neuron_id : signal is "XIL_INTERFACENAME spike_in_neuron_id, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_in_weight : signal is "xilinx.com:signal:data:1.0 spike_in_weight DATA";
  attribute X_INTERFACE_MODE of spike_in_weight : signal is "master";
  attribute X_INTERFACE_PARAMETER of spike_in_weight : signal is "XIL_INTERFACENAME spike_in_weight, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_in_ready : signal is "xilinx.com:signal:data:1.0 spike_in_ready DATA";
  attribute X_INTERFACE_MODE of spike_in_ready : signal is "slave";
  attribute X_INTERFACE_PARAMETER of spike_in_ready : signal is "XIL_INTERFACENAME spike_in_ready, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_out_valid : signal is "xilinx.com:signal:data:1.0 spike_out_valid DATA";
  attribute X_INTERFACE_MODE of spike_out_valid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of spike_out_valid : signal is "XIL_INTERFACENAME spike_out_valid, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_out_neuron_id : signal is "xilinx.com:signal:data:1.0 spike_out_neuron_id DATA";
  attribute X_INTERFACE_MODE of spike_out_neuron_id : signal is "slave";
  attribute X_INTERFACE_PARAMETER of spike_out_neuron_id : signal is "XIL_INTERFACENAME spike_out_neuron_id, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_out_weight : signal is "xilinx.com:signal:data:1.0 spike_out_weight DATA";
  attribute X_INTERFACE_MODE of spike_out_weight : signal is "slave";
  attribute X_INTERFACE_PARAMETER of spike_out_weight : signal is "XIL_INTERFACENAME spike_out_weight, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of spike_out_ready : signal is "xilinx.com:signal:data:1.0 spike_out_ready DATA";
  attribute X_INTERFACE_MODE of spike_out_ready : signal is "master";
  attribute X_INTERFACE_PARAMETER of spike_out_ready : signal is "XIL_INTERFACENAME spike_out_ready, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_valid : signal is "xilinx.com:signal:data:1.0 learn_weight_valid DATA";
  attribute X_INTERFACE_MODE of learn_weight_valid : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_valid : signal is "XIL_INTERFACENAME learn_weight_valid, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_group : signal is "xilinx.com:signal:data:1.0 learn_weight_group DATA";
  attribute X_INTERFACE_MODE of learn_weight_group : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_group : signal is "XIL_INTERFACENAME learn_weight_group, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_src : signal is "xilinx.com:signal:data:1.0 learn_weight_src DATA";
  attribute X_INTERFACE_MODE of learn_weight_src : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_src : signal is "XIL_INTERFACENAME learn_weight_src, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_dst : signal is "xilinx.com:signal:data:1.0 learn_weight_dst DATA";
  attribute X_INTERFACE_MODE of learn_weight_dst : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_dst : signal is "XIL_INTERFACENAME learn_weight_dst, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_data : signal is "xilinx.com:signal:data:1.0 learn_weight_data DATA";
  attribute X_INTERFACE_MODE of learn_weight_data : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_data : signal is "XIL_INTERFACENAME learn_weight_data, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_exc : signal is "xilinx.com:signal:data:1.0 learn_weight_exc DATA";
  attribute X_INTERFACE_MODE of learn_weight_exc : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_exc : signal is "XIL_INTERFACENAME learn_weight_exc, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_is_inter : signal is "xilinx.com:signal:data:1.0 learn_weight_is_inter DATA";
  attribute X_INTERFACE_MODE of learn_weight_is_inter : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_is_inter : signal is "XIL_INTERFACENAME learn_weight_is_inter, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_dst_group : signal is "xilinx.com:signal:data:1.0 learn_weight_dst_group DATA";
  attribute X_INTERFACE_MODE of learn_weight_dst_group : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_dst_group : signal is "XIL_INTERFACENAME learn_weight_dst_group, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_fanout_idx : signal is "xilinx.com:signal:data:1.0 learn_weight_fanout_idx DATA";
  attribute X_INTERFACE_MODE of learn_weight_fanout_idx : signal is "master";
  attribute X_INTERFACE_PARAMETER of learn_weight_fanout_idx : signal is "XIL_INTERFACENAME learn_weight_fanout_idx, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of learn_weight_ready : signal is "xilinx.com:signal:data:1.0 learn_weight_ready DATA";
  attribute X_INTERFACE_MODE of learn_weight_ready : signal is "slave";
  attribute X_INTERFACE_PARAMETER of learn_weight_ready : signal is "XIL_INTERFACENAME learn_weight_ready, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of snn_enable : signal is "xilinx.com:signal:data:1.0 snn_enable DATA";
  attribute X_INTERFACE_MODE of snn_enable : signal is "master";
  attribute X_INTERFACE_PARAMETER of snn_enable : signal is "XIL_INTERFACENAME snn_enable, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of snn_reset : signal is "xilinx.com:signal:data:1.0 snn_reset DATA";
  attribute X_INTERFACE_MODE of snn_reset : signal is "master";
  attribute X_INTERFACE_PARAMETER of snn_reset : signal is "XIL_INTERFACENAME snn_reset, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of threshold_out : signal is "xilinx.com:signal:data:1.0 threshold_out DATA";
  attribute X_INTERFACE_MODE of threshold_out : signal is "master";
  attribute X_INTERFACE_PARAMETER of threshold_out : signal is "XIL_INTERFACENAME threshold_out, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of leak_rate_out : signal is "xilinx.com:signal:data:1.0 leak_rate_out DATA";
  attribute X_INTERFACE_MODE of leak_rate_out : signal is "master";
  attribute X_INTERFACE_PARAMETER of leak_rate_out : signal is "XIL_INTERFACENAME leak_rate_out, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of snn_ready : signal is "xilinx.com:signal:data:1.0 snn_ready DATA";
  attribute X_INTERFACE_MODE of snn_ready : signal is "slave";
  attribute X_INTERFACE_PARAMETER of snn_ready : signal is "XIL_INTERFACENAME snn_ready, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of snn_busy : signal is "xilinx.com:signal:data:1.0 snn_busy DATA";
  attribute X_INTERFACE_MODE of snn_busy : signal is "slave";
  attribute X_INTERFACE_PARAMETER of snn_busy : signal is "XIL_INTERFACENAME snn_busy, LAYERED_METADATA undef";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "snn_top_hls,Vivado 2025.2";
begin
end;
