// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        base_offset,
        add_ln265_1,
        CONNECTION_TABLE_dst_id_start_load,
        sext_ln294,
        sext_ln168,
        learn_weight_ready,
        pre_id,
        src_group,
        empty,
        post_traces_address0,
        post_traces_ce0,
        post_traces_q0,
        weight_memory_address0,
        weight_memory_ce0,
        weight_memory_we0,
        weight_memory_d0,
        weight_memory_address1,
        weight_memory_ce1,
        weight_memory_q1,
        learn_bridge_valid_i,
        learn_bridge_valid_o,
        learn_bridge_valid_o_ap_vld,
        learn_bridge_group,
        learn_bridge_group_ap_vld,
        learn_bridge_src,
        learn_bridge_src_ap_vld,
        learn_bridge_dst,
        learn_bridge_dst_ap_vld,
        learn_bridge_data,
        learn_bridge_data_ap_vld,
        learn_bridge_exc,
        learn_bridge_exc_ap_vld,
        learn_bridge_is_inter,
        learn_bridge_is_inter_ap_vld,
        learn_bridge_dst_group,
        learn_bridge_dst_group_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] base_offset;
input  [23:0] add_ln265_1;
input  [12:0] CONNECTION_TABLE_dst_id_start_load;
input  [15:0] sext_ln294;
input  [15:0] sext_ln168;
input  [0:0] learn_weight_ready;
input  [6:0] pre_id;
input  [3:0] src_group;
input  [1:0] empty;
output  [12:0] post_traces_address0;
output   post_traces_ce0;
input  [7:0] post_traces_q0;
output  [19:0] weight_memory_address0;
output   weight_memory_ce0;
output   weight_memory_we0;
output  [3:0] weight_memory_d0;
output  [19:0] weight_memory_address1;
output   weight_memory_ce1;
input  [3:0] weight_memory_q1;
input  [0:0] learn_bridge_valid_i;
output  [0:0] learn_bridge_valid_o;
output   learn_bridge_valid_o_ap_vld;
output  [3:0] learn_bridge_group;
output   learn_bridge_group_ap_vld;
output  [6:0] learn_bridge_src;
output   learn_bridge_src_ap_vld;
output  [6:0] learn_bridge_dst;
output   learn_bridge_dst_ap_vld;
output  [3:0] learn_bridge_data;
output   learn_bridge_data_ap_vld;
output  [0:0] learn_bridge_exc;
output   learn_bridge_exc_ap_vld;
output  [0:0] learn_bridge_is_inter;
output   learn_bridge_is_inter_ap_vld;
output  [3:0] learn_bridge_dst_group;
output   learn_bridge_dst_group_ap_vld;

reg ap_idle;
reg[0:0] learn_bridge_valid_o;
reg learn_bridge_valid_o_ap_vld;
reg learn_bridge_group_ap_vld;
reg learn_bridge_src_ap_vld;
reg learn_bridge_dst_ap_vld;
reg learn_bridge_data_ap_vld;
reg learn_bridge_exc_ap_vld;
reg learn_bridge_is_inter_ap_vld;
reg learn_bridge_dst_group_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln265_fu_280_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [27:0] sext_ln294_cast_fu_256_p1;
reg  signed [27:0] sext_ln294_cast_reg_633;
wire  signed [27:0] sext_ln168_cast_fu_260_p1;
reg  signed [27:0] sext_ln168_cast_reg_638;
reg   [23:0] widx_1_reg_643;
wire   [12:0] post_id_fu_295_p2;
reg   [12:0] post_id_reg_652;
reg   [7:0] post_trace_val_reg_664;
reg   [7:0] post_trace_val_reg_664_pp0_iter3_reg;
reg   [7:0] post_trace_val_reg_664_pp0_iter4_reg;
wire   [0:0] icmp_ln276_fu_325_p2;
reg   [0:0] icmp_ln276_reg_669;
reg   [0:0] icmp_ln276_reg_669_pp0_iter3_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter4_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter5_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter6_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter7_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter8_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter9_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter10_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter11_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter12_reg;
reg   [0:0] icmp_ln276_reg_669_pp0_iter13_reg;
reg   [19:0] weight_memory_addr_reg_673;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter3_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter4_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter5_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter6_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter7_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter8_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter9_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter10_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter11_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter12_reg;
reg   [19:0] weight_memory_addr_reg_673_pp0_iter13_reg;
wire   [0:0] or_ln163_fu_341_p2;
reg   [0:0] or_ln163_reg_679;
reg   [0:0] or_ln163_reg_679_pp0_iter3_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter4_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter5_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter6_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter7_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter8_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter9_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter10_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter11_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter12_reg;
reg   [0:0] or_ln163_reg_679_pp0_iter13_reg;
wire   [0:0] icmp_ln168_fu_360_p2;
reg   [0:0] icmp_ln168_reg_683;
reg   [0:0] icmp_ln168_reg_683_pp0_iter3_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter4_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter5_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter6_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter7_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter8_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter9_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter10_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter11_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter12_reg;
reg   [0:0] icmp_ln168_reg_683_pp0_iter13_reg;
reg  signed [3:0] current_w_reg_687;
reg  signed [3:0] current_w_reg_687_pp0_iter6_reg;
reg  signed [3:0] current_w_reg_687_pp0_iter7_reg;
reg  signed [3:0] current_w_reg_687_pp0_iter8_reg;
reg  signed [3:0] current_w_reg_687_pp0_iter9_reg;
reg  signed [3:0] current_w_reg_687_pp0_iter10_reg;
reg  signed [3:0] current_w_reg_687_pp0_iter11_reg;
reg  signed [3:0] current_w_reg_687_pp0_iter12_reg;
wire   [3:0] updated_fu_543_p3;
reg   [3:0] updated_reg_712;
wire   [63:0] zext_ln272_fu_300_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln265_fu_321_p1;
wire   [3:0] dst_group_fu_366_p4;
reg   [10:0] jj_fu_164;
wire   [10:0] add_ln265_fu_285_p2;
wire    ap_loop_init;
reg   [23:0] widx_fu_168;
wire   [23:0] add_ln309_fu_305_p2;
reg    post_traces_ce0_local;
reg    weight_memory_ce1_local;
reg    weight_memory_we0_local;
reg    weight_memory_ce0_local;
wire   [12:0] zext_ln265_1_fu_291_p1;
wire   [0:0] xor_ln163_fu_335_p2;
wire   [1:0] tmp_23_fu_346_p4;
wire   [1:0] or_ln168_fu_355_p2;
wire  signed [3:0] bit_sel_fu_417_p1;
wire   [0:0] bit_sel_fu_417_p3;
wire  signed [3:0] trunc_ln282_fu_431_p0;
wire   [0:0] xor_ln282_fu_425_p2;
wire   [2:0] trunc_ln282_fu_431_p1;
wire   [3:0] distance_fu_435_p3;
wire   [3:0] grp_fu_450_p0;
wire   [7:0] grp_fu_450_p1;
wire   [11:0] grp_fu_450_p2;
wire   [11:0] grp_fu_460_p0;
wire  signed [15:0] grp_fu_460_p1;
wire   [27:0] grp_fu_460_p2;
wire  signed [11:0] trunc_ln8_fu_465_p4;
wire  signed [15:0] grp_fu_479_p1;
wire   [27:0] grp_fu_479_p2;
wire  signed [15:0] sext_ln282_fu_484_p1;
wire   [15:0] trunc_ln9_fu_487_p4;
wire   [15:0] w_fu_497_p2;
wire   [12:0] tmp_22_fu_503_p4;
wire   [0:0] icmp_ln131_fu_513_p2;
wire   [0:0] icmp_ln132_fu_519_p2;
wire   [0:0] or_ln131_fu_537_p2;
wire   [3:0] select_ln131_fu_529_p3;
wire   [3:0] trunc_ln133_fu_525_p1;
wire   [0:0] tmp_24_fu_551_p3;
wire   [3:0] mag_1_fu_564_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [11:0] grp_fu_450_p00;
wire   [11:0] grp_fu_450_p10;
wire   [27:0] grp_fu_460_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 jj_fu_164 = 11'd0;
#0 widx_fu_168 = 24'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_mul_4ns_8ns_12_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 12 ))
mul_4ns_8ns_12_3_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_450_p0),
    .din1(grp_fu_450_p1),
    .ce(1'b1),
    .dout(grp_fu_450_p2)
);

snn_top_hls_mul_12ns_16s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12ns_16s_28_4_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_460_p0),
    .din1(grp_fu_460_p1),
    .ce(1'b1),
    .dout(grp_fu_460_p2)
);

snn_top_hls_mul_12s_16s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12s_16s_28_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln8_fu_465_p4),
    .din1(grp_fu_479_p1),
    .ce(1'b1),
    .dout(grp_fu_479_p2)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            jj_fu_164 <= 11'd0;
        end else if (((icmp_ln265_fu_280_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            jj_fu_164 <= add_ln265_fu_285_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            widx_fu_168 <= base_offset;
        end else if (((icmp_ln265_fu_280_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            widx_fu_168 <= add_ln309_fu_305_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        current_w_reg_687_pp0_iter10_reg <= current_w_reg_687_pp0_iter9_reg;
        current_w_reg_687_pp0_iter11_reg <= current_w_reg_687_pp0_iter10_reg;
        current_w_reg_687_pp0_iter12_reg <= current_w_reg_687_pp0_iter11_reg;
        current_w_reg_687_pp0_iter6_reg <= current_w_reg_687;
        current_w_reg_687_pp0_iter7_reg <= current_w_reg_687_pp0_iter6_reg;
        current_w_reg_687_pp0_iter8_reg <= current_w_reg_687_pp0_iter7_reg;
        current_w_reg_687_pp0_iter9_reg <= current_w_reg_687_pp0_iter8_reg;
        icmp_ln168_reg_683 <= icmp_ln168_fu_360_p2;
        icmp_ln168_reg_683_pp0_iter10_reg <= icmp_ln168_reg_683_pp0_iter9_reg;
        icmp_ln168_reg_683_pp0_iter11_reg <= icmp_ln168_reg_683_pp0_iter10_reg;
        icmp_ln168_reg_683_pp0_iter12_reg <= icmp_ln168_reg_683_pp0_iter11_reg;
        icmp_ln168_reg_683_pp0_iter13_reg <= icmp_ln168_reg_683_pp0_iter12_reg;
        icmp_ln168_reg_683_pp0_iter3_reg <= icmp_ln168_reg_683;
        icmp_ln168_reg_683_pp0_iter4_reg <= icmp_ln168_reg_683_pp0_iter3_reg;
        icmp_ln168_reg_683_pp0_iter5_reg <= icmp_ln168_reg_683_pp0_iter4_reg;
        icmp_ln168_reg_683_pp0_iter6_reg <= icmp_ln168_reg_683_pp0_iter5_reg;
        icmp_ln168_reg_683_pp0_iter7_reg <= icmp_ln168_reg_683_pp0_iter6_reg;
        icmp_ln168_reg_683_pp0_iter8_reg <= icmp_ln168_reg_683_pp0_iter7_reg;
        icmp_ln168_reg_683_pp0_iter9_reg <= icmp_ln168_reg_683_pp0_iter8_reg;
        icmp_ln276_reg_669 <= icmp_ln276_fu_325_p2;
        icmp_ln276_reg_669_pp0_iter10_reg <= icmp_ln276_reg_669_pp0_iter9_reg;
        icmp_ln276_reg_669_pp0_iter11_reg <= icmp_ln276_reg_669_pp0_iter10_reg;
        icmp_ln276_reg_669_pp0_iter12_reg <= icmp_ln276_reg_669_pp0_iter11_reg;
        icmp_ln276_reg_669_pp0_iter13_reg <= icmp_ln276_reg_669_pp0_iter12_reg;
        icmp_ln276_reg_669_pp0_iter3_reg <= icmp_ln276_reg_669;
        icmp_ln276_reg_669_pp0_iter4_reg <= icmp_ln276_reg_669_pp0_iter3_reg;
        icmp_ln276_reg_669_pp0_iter5_reg <= icmp_ln276_reg_669_pp0_iter4_reg;
        icmp_ln276_reg_669_pp0_iter6_reg <= icmp_ln276_reg_669_pp0_iter5_reg;
        icmp_ln276_reg_669_pp0_iter7_reg <= icmp_ln276_reg_669_pp0_iter6_reg;
        icmp_ln276_reg_669_pp0_iter8_reg <= icmp_ln276_reg_669_pp0_iter7_reg;
        icmp_ln276_reg_669_pp0_iter9_reg <= icmp_ln276_reg_669_pp0_iter8_reg;
        or_ln163_reg_679 <= or_ln163_fu_341_p2;
        or_ln163_reg_679_pp0_iter10_reg <= or_ln163_reg_679_pp0_iter9_reg;
        or_ln163_reg_679_pp0_iter11_reg <= or_ln163_reg_679_pp0_iter10_reg;
        or_ln163_reg_679_pp0_iter12_reg <= or_ln163_reg_679_pp0_iter11_reg;
        or_ln163_reg_679_pp0_iter13_reg <= or_ln163_reg_679_pp0_iter12_reg;
        or_ln163_reg_679_pp0_iter3_reg <= or_ln163_reg_679;
        or_ln163_reg_679_pp0_iter4_reg <= or_ln163_reg_679_pp0_iter3_reg;
        or_ln163_reg_679_pp0_iter5_reg <= or_ln163_reg_679_pp0_iter4_reg;
        or_ln163_reg_679_pp0_iter6_reg <= or_ln163_reg_679_pp0_iter5_reg;
        or_ln163_reg_679_pp0_iter7_reg <= or_ln163_reg_679_pp0_iter6_reg;
        or_ln163_reg_679_pp0_iter8_reg <= or_ln163_reg_679_pp0_iter7_reg;
        or_ln163_reg_679_pp0_iter9_reg <= or_ln163_reg_679_pp0_iter8_reg;
        post_trace_val_reg_664 <= post_traces_q0;
        post_trace_val_reg_664_pp0_iter3_reg <= post_trace_val_reg_664;
        post_trace_val_reg_664_pp0_iter4_reg <= post_trace_val_reg_664_pp0_iter3_reg;
        updated_reg_712 <= updated_fu_543_p3;
        weight_memory_addr_reg_673 <= zext_ln265_fu_321_p1;
        weight_memory_addr_reg_673_pp0_iter10_reg <= weight_memory_addr_reg_673_pp0_iter9_reg;
        weight_memory_addr_reg_673_pp0_iter11_reg <= weight_memory_addr_reg_673_pp0_iter10_reg;
        weight_memory_addr_reg_673_pp0_iter12_reg <= weight_memory_addr_reg_673_pp0_iter11_reg;
        weight_memory_addr_reg_673_pp0_iter13_reg <= weight_memory_addr_reg_673_pp0_iter12_reg;
        weight_memory_addr_reg_673_pp0_iter3_reg <= weight_memory_addr_reg_673;
        weight_memory_addr_reg_673_pp0_iter4_reg <= weight_memory_addr_reg_673_pp0_iter3_reg;
        weight_memory_addr_reg_673_pp0_iter5_reg <= weight_memory_addr_reg_673_pp0_iter4_reg;
        weight_memory_addr_reg_673_pp0_iter6_reg <= weight_memory_addr_reg_673_pp0_iter5_reg;
        weight_memory_addr_reg_673_pp0_iter7_reg <= weight_memory_addr_reg_673_pp0_iter6_reg;
        weight_memory_addr_reg_673_pp0_iter8_reg <= weight_memory_addr_reg_673_pp0_iter7_reg;
        weight_memory_addr_reg_673_pp0_iter9_reg <= weight_memory_addr_reg_673_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        post_id_reg_652 <= post_id_fu_295_p2;
        sext_ln168_cast_reg_638 <= sext_ln168_cast_fu_260_p1;
        sext_ln294_cast_reg_633 <= sext_ln294_cast_fu_256_p1;
        widx_1_reg_643 <= widx_fu_168;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        current_w_reg_687 <= weight_memory_q1;
    end
end

always @ (*) begin
    if (((icmp_ln265_fu_280_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln168_reg_683_pp0_iter13_reg == 1'd1) & (or_ln163_reg_679_pp0_iter13_reg == 1'd1) & (icmp_ln276_reg_669_pp0_iter13_reg == 1'd0))) begin
        learn_bridge_data_ap_vld = 1'b1;
    end else begin
        learn_bridge_data_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_dst_ap_vld = 1'b1;
    end else begin
        learn_bridge_dst_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_dst_group_ap_vld = 1'b1;
    end else begin
        learn_bridge_dst_group_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln168_reg_683_pp0_iter13_reg == 1'd1) & (or_ln163_reg_679_pp0_iter13_reg == 1'd1) & (icmp_ln276_reg_669_pp0_iter13_reg == 1'd0))) begin
        learn_bridge_exc_ap_vld = 1'b1;
    end else begin
        learn_bridge_exc_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_group_ap_vld = 1'b1;
    end else begin
        learn_bridge_group_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_is_inter_ap_vld = 1'b1;
    end else begin
        learn_bridge_is_inter_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_src_ap_vld = 1'b1;
    end else begin
        learn_bridge_src_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_valid_o = 1'd1;
    end else begin
        learn_bridge_valid_o = learn_bridge_valid_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln168_fu_360_p2 == 1'd1) & (or_ln163_fu_341_p2 == 1'd1) & (icmp_ln276_fu_325_p2 == 1'd0))) begin
        learn_bridge_valid_o_ap_vld = 1'b1;
    end else begin
        learn_bridge_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        post_traces_ce0_local = 1'b1;
    end else begin
        post_traces_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        weight_memory_ce0_local = 1'b1;
    end else begin
        weight_memory_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        weight_memory_ce1_local = 1'b1;
    end else begin
        weight_memory_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln276_reg_669_pp0_iter13_reg == 1'd0))) begin
        weight_memory_we0_local = 1'b1;
    end else begin
        weight_memory_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln265_fu_285_p2 = (jj_fu_164 + 11'd1);

assign add_ln309_fu_305_p2 = (widx_fu_168 + 24'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel_fu_417_p1 = weight_memory_q1;

assign bit_sel_fu_417_p3 = bit_sel_fu_417_p1[4'd3];

assign distance_fu_435_p3 = {{xor_ln282_fu_425_p2}, {trunc_ln282_fu_431_p1}};

assign dst_group_fu_366_p4 = {{post_id_reg_652[10:7]}};

assign grp_fu_450_p0 = grp_fu_450_p00;

assign grp_fu_450_p00 = distance_fu_435_p3;

assign grp_fu_450_p1 = grp_fu_450_p10;

assign grp_fu_450_p10 = post_trace_val_reg_664_pp0_iter4_reg;

assign grp_fu_460_p0 = grp_fu_460_p00;

assign grp_fu_460_p00 = grp_fu_450_p2;

assign grp_fu_460_p1 = sext_ln294_cast_reg_633;

assign grp_fu_479_p1 = sext_ln168_cast_reg_638;

assign icmp_ln131_fu_513_p2 = (($signed(tmp_22_fu_503_p4) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_519_p2 = (($signed(w_fu_497_p2) < $signed(16'd65528)) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_360_p2 = ((or_ln168_fu_355_p2 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln265_fu_280_p2 = ((widx_fu_168 == add_ln265_1) ? 1'b1 : 1'b0);

assign icmp_ln276_fu_325_p2 = ((post_traces_q0 == 8'd0) ? 1'b1 : 1'b0);

assign learn_bridge_data = ((tmp_24_fu_551_p3[0:0] == 1'b1) ? mag_1_fu_564_p2 : updated_reg_712);

assign learn_bridge_dst = post_id_reg_652[6:0];

assign learn_bridge_dst_group = {{post_id_reg_652[10:7]}};

assign learn_bridge_exc = (tmp_24_fu_551_p3 ^ 1'd1);

assign learn_bridge_group = src_group;

assign learn_bridge_is_inter = ((src_group != dst_group_fu_366_p4) ? 1'b1 : 1'b0);

assign learn_bridge_src = pre_id;

assign mag_1_fu_564_p2 = (4'd0 - updated_reg_712);

assign or_ln131_fu_537_p2 = (icmp_ln132_fu_519_p2 | icmp_ln131_fu_513_p2);

assign or_ln163_fu_341_p2 = (xor_ln163_fu_335_p2 | learn_weight_ready);

assign or_ln168_fu_355_p2 = (tmp_23_fu_346_p4 | empty);

assign post_id_fu_295_p2 = (zext_ln265_1_fu_291_p1 + CONNECTION_TABLE_dst_id_start_load);

assign post_traces_address0 = zext_ln272_fu_300_p1;

assign post_traces_ce0 = post_traces_ce0_local;

assign select_ln131_fu_529_p3 = ((icmp_ln131_fu_513_p2[0:0] == 1'b1) ? 4'd7 : 4'd8);

assign sext_ln168_cast_fu_260_p1 = $signed(sext_ln168);

assign sext_ln282_fu_484_p1 = current_w_reg_687_pp0_iter12_reg;

assign sext_ln294_cast_fu_256_p1 = $signed(sext_ln294);

assign tmp_22_fu_503_p4 = {{w_fu_497_p2[15:3]}};

assign tmp_23_fu_346_p4 = {{post_id_reg_652[12:11]}};

assign tmp_24_fu_551_p3 = updated_reg_712[32'd3];

assign trunc_ln133_fu_525_p1 = w_fu_497_p2[3:0];

assign trunc_ln282_fu_431_p0 = weight_memory_q1;

assign trunc_ln282_fu_431_p1 = trunc_ln282_fu_431_p0[2:0];

assign trunc_ln8_fu_465_p4 = {{grp_fu_460_p2[27:16]}};

assign trunc_ln9_fu_487_p4 = {{grp_fu_479_p2[23:8]}};

assign updated_fu_543_p3 = ((or_ln131_fu_537_p2[0:0] == 1'b1) ? select_ln131_fu_529_p3 : trunc_ln133_fu_525_p1);

assign w_fu_497_p2 = ($signed(sext_ln282_fu_484_p1) - $signed(trunc_ln9_fu_487_p4));

assign weight_memory_address0 = weight_memory_addr_reg_673_pp0_iter13_reg;

assign weight_memory_address1 = zext_ln265_fu_321_p1;

assign weight_memory_ce0 = weight_memory_ce0_local;

assign weight_memory_ce1 = weight_memory_ce1_local;

assign weight_memory_d0 = updated_reg_712;

assign weight_memory_we0 = weight_memory_we0_local;

assign xor_ln163_fu_335_p2 = (learn_bridge_valid_i ^ 1'd1);

assign xor_ln282_fu_425_p2 = (bit_sel_fu_417_p3 ^ 1'd1);

assign zext_ln265_1_fu_291_p1 = jj_fu_164;

assign zext_ln265_fu_321_p1 = widx_1_reg_643;

assign zext_ln272_fu_300_p1 = post_id_fu_295_p2;

endmodule //snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP
