// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_ENCODER_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        encoder_spikes_din,
        encoder_spikes_full_n,
        encoder_spikes_write,
        empty,
        encoder_config_num_channels,
        encoder_config_delta_threshold,
        encoder_config_delta_decay,
        time_r,
        encoder_config_default_weight,
        encoder_spike_counter_flag_3_out,
        encoder_spike_counter_flag_3_out_ap_vld,
        encoder_spike_counter_new_3_out,
        encoder_spike_counter_new_3_out_ap_vld,
        encoder_spike_counter_loc_3_out_i,
        encoder_spike_counter_loc_3_out_o,
        encoder_spike_counter_loc_3_out_o_ap_vld,
        p_ZL13encoder_frame_0_address0,
        p_ZL13encoder_frame_0_ce0,
        p_ZL13encoder_frame_0_q0,
        p_ZL13encoder_frame_1_address0,
        p_ZL13encoder_frame_1_ce0,
        p_ZL13encoder_frame_1_q0,
        p_ZL17encoder_phase_acc_0_address0,
        p_ZL17encoder_phase_acc_0_ce0,
        p_ZL17encoder_phase_acc_0_q0,
        p_ZL17encoder_phase_acc_0_address1,
        p_ZL17encoder_phase_acc_0_ce1,
        p_ZL17encoder_phase_acc_0_we1,
        p_ZL17encoder_phase_acc_0_d1,
        p_ZL17encoder_phase_acc_1_address0,
        p_ZL17encoder_phase_acc_1_ce0,
        p_ZL17encoder_phase_acc_1_q0,
        p_ZL17encoder_phase_acc_1_address1,
        p_ZL17encoder_phase_acc_1_ce1,
        p_ZL17encoder_phase_acc_1_we1,
        p_ZL17encoder_phase_acc_1_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [40:0] encoder_spikes_din;
input   encoder_spikes_full_n;
output   encoder_spikes_write;
input  [3:0] empty;
input  [15:0] encoder_config_num_channels;
input  [15:0] encoder_config_delta_threshold;
input  [15:0] encoder_config_delta_decay;
input  [10:0] time_r;
input  [7:0] encoder_config_default_weight;
output  [0:0] encoder_spike_counter_flag_3_out;
output   encoder_spike_counter_flag_3_out_ap_vld;
output  [31:0] encoder_spike_counter_new_3_out;
output   encoder_spike_counter_new_3_out_ap_vld;
input  [31:0] encoder_spike_counter_loc_3_out_i;
output  [31:0] encoder_spike_counter_loc_3_out_o;
output   encoder_spike_counter_loc_3_out_o_ap_vld;
output  [8:0] p_ZL13encoder_frame_0_address0;
output   p_ZL13encoder_frame_0_ce0;
input  [7:0] p_ZL13encoder_frame_0_q0;
output  [8:0] p_ZL13encoder_frame_1_address0;
output   p_ZL13encoder_frame_1_ce0;
input  [7:0] p_ZL13encoder_frame_1_q0;
output  [8:0] p_ZL17encoder_phase_acc_0_address0;
output   p_ZL17encoder_phase_acc_0_ce0;
input  [15:0] p_ZL17encoder_phase_acc_0_q0;
output  [8:0] p_ZL17encoder_phase_acc_0_address1;
output   p_ZL17encoder_phase_acc_0_ce1;
output   p_ZL17encoder_phase_acc_0_we1;
output  [15:0] p_ZL17encoder_phase_acc_0_d1;
output  [8:0] p_ZL17encoder_phase_acc_1_address0;
output   p_ZL17encoder_phase_acc_1_ce0;
input  [15:0] p_ZL17encoder_phase_acc_1_q0;
output  [8:0] p_ZL17encoder_phase_acc_1_address1;
output   p_ZL17encoder_phase_acc_1_ce1;
output   p_ZL17encoder_phase_acc_1_we1;
output  [15:0] p_ZL17encoder_phase_acc_1_d1;

reg ap_idle;
reg encoder_spikes_write;
reg encoder_spike_counter_flag_3_out_ap_vld;
reg encoder_spike_counter_new_3_out_ap_vld;
reg[31:0] encoder_spike_counter_loc_3_out_o;
reg encoder_spike_counter_loc_3_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln95_reg_409;
reg   [0:0] icmp_ln95_reg_409_pp0_iter1_reg;
reg   [0:0] icmp_ln99_reg_395;
reg   [0:0] icmp_ln77_reg_446;
reg   [0:0] tmp_1_reg_450;
reg    ap_predicate_op71_write_state4;
reg    ap_block_state4_pp0_stage1_iter1_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln93_reg_405;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    encoder_spikes_blk_n;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln99_fu_205_p2;
reg   [9:0] ch_1_reg_399;
reg   [9:0] ch_1_reg_399_pp0_iter1_reg;
wire   [0:0] icmp_ln93_fu_219_p2;
wire   [0:0] icmp_ln95_fu_253_p2;
reg   [8:0] p_ZL17encoder_phase_acc_0_addr_reg_423;
reg   [8:0] p_ZL17encoder_phase_acc_0_addr_reg_423_pp0_iter1_reg;
reg   [8:0] p_ZL17encoder_phase_acc_1_addr_reg_429;
reg   [8:0] p_ZL17encoder_phase_acc_1_addr_reg_429_pp0_iter1_reg;
wire   [0:0] trunc_ln93_fu_264_p1;
reg   [0:0] trunc_ln93_reg_435;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [15:0] add_ln69_fu_287_p2;
reg   [15:0] add_ln69_reg_439;
wire   [0:0] icmp_ln77_fu_310_p2;
wire   [15:0] sub_ln79_fu_315_p2;
reg   [15:0] sub_ln79_reg_454;
wire   [63:0] zext_ln93_1_fu_245_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1_grp0;
wire   [31:0] add_ln55_fu_342_p2;
reg   [9:0] ch_fu_90;
wire   [9:0] ch_2_fu_225_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_ch_1;
reg    ap_block_pp0_stage1_01001_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg    p_ZL13encoder_frame_0_ce0_local;
reg    p_ZL13encoder_frame_1_ce0_local;
reg    p_ZL17encoder_phase_acc_0_ce0_local;
reg    p_ZL17encoder_phase_acc_0_we1_local;
reg   [15:0] p_ZL17encoder_phase_acc_0_d1_local;
wire   [15:0] select_ln72_fu_301_p3;
reg    p_ZL17encoder_phase_acc_0_ce1_local;
reg   [8:0] p_ZL17encoder_phase_acc_0_address1_local;
reg    p_ZL17encoder_phase_acc_1_ce0_local;
reg    p_ZL17encoder_phase_acc_1_we1_local;
reg   [15:0] p_ZL17encoder_phase_acc_1_d1_local;
reg    p_ZL17encoder_phase_acc_1_ce1_local;
reg   [8:0] p_ZL17encoder_phase_acc_1_address1_local;
wire   [8:0] lshr_ln1_fu_235_p4;
wire   [15:0] zext_ln93_fu_231_p1;
wire   [7:0] value_fu_267_p3;
wire   [15:0] select_ln69_fu_279_p3;
wire   [15:0] zext_ln68_fu_275_p1;
wire   [0:0] icmp_ln72_fu_293_p2;
wire   [15:0] sub_ln73_fu_297_p2;
wire   [12:0] zext_ln48_fu_324_p1;
wire   [32:0] or_ln54_3_fu_327_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ch_fu_90 = 10'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln93_fu_219_p2 == 1'd0))) begin
            ch_fu_90 <= ch_2_fu_225_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ch_fu_90 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln69_reg_439 <= add_ln69_fu_287_p2;
        trunc_ln93_reg_435 <= trunc_ln93_fu_264_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch_1_reg_399 <= ap_sig_allocacmp_ch_1;
        ch_1_reg_399_pp0_iter1_reg <= ch_1_reg_399;
        icmp_ln77_reg_446 <= icmp_ln77_fu_310_p2;
        icmp_ln93_reg_405 <= icmp_ln93_fu_219_p2;
        icmp_ln95_reg_409 <= icmp_ln95_fu_253_p2;
        icmp_ln95_reg_409_pp0_iter1_reg <= icmp_ln95_reg_409;
        icmp_ln99_reg_395 <= icmp_ln99_fu_205_p2;
        p_ZL17encoder_phase_acc_0_addr_reg_423 <= zext_ln93_1_fu_245_p1;
        p_ZL17encoder_phase_acc_0_addr_reg_423_pp0_iter1_reg <= p_ZL17encoder_phase_acc_0_addr_reg_423;
        p_ZL17encoder_phase_acc_1_addr_reg_429 <= zext_ln93_1_fu_245_p1;
        p_ZL17encoder_phase_acc_1_addr_reg_429_pp0_iter1_reg <= p_ZL17encoder_phase_acc_1_addr_reg_429;
        sub_ln79_reg_454 <= sub_ln79_fu_315_p2;
        tmp_1_reg_450 <= encoder_spikes_full_n;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_405 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ch_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_ch_1 = ch_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (tmp_1_reg_450 == 1'd1) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        encoder_spike_counter_flag_3_out_ap_vld = 1'b1;
    end else begin
        encoder_spike_counter_flag_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_grp0) & (tmp_1_reg_450 == 1'd1) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        encoder_spike_counter_loc_3_out_o = add_ln55_fu_342_p2;
    end else begin
        encoder_spike_counter_loc_3_out_o = encoder_spike_counter_loc_3_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (tmp_1_reg_450 == 1'd1) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        encoder_spike_counter_loc_3_out_o_ap_vld = 1'b1;
    end else begin
        encoder_spike_counter_loc_3_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (tmp_1_reg_450 == 1'd1) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        encoder_spike_counter_new_3_out_ap_vld = 1'b1;
    end else begin
        encoder_spike_counter_new_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_predicate_op71_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        encoder_spikes_blk_n = encoder_spikes_full_n;
    end else begin
        encoder_spikes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_predicate_op71_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        encoder_spikes_write = 1'b1;
    end else begin
        encoder_spikes_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13encoder_frame_0_ce0_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13encoder_frame_1_ce0_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL17encoder_phase_acc_0_address1_local = p_ZL17encoder_phase_acc_0_addr_reg_423_pp0_iter1_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL17encoder_phase_acc_0_address1_local = p_ZL17encoder_phase_acc_0_addr_reg_423;
        end else begin
            p_ZL17encoder_phase_acc_0_address1_local = 'bx;
        end
    end else begin
        p_ZL17encoder_phase_acc_0_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17encoder_phase_acc_0_ce0_local = 1'b1;
    end else begin
        p_ZL17encoder_phase_acc_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL17encoder_phase_acc_0_ce1_local = 1'b1;
    end else begin
        p_ZL17encoder_phase_acc_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL17encoder_phase_acc_0_d1_local = sub_ln79_reg_454;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL17encoder_phase_acc_0_d1_local = select_ln72_fu_301_p3;
        end else begin
            p_ZL17encoder_phase_acc_0_d1_local = 'bx;
        end
    end else begin
        p_ZL17encoder_phase_acc_0_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln93_reg_435 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln93_reg_435 == 1'd0)))) begin
        p_ZL17encoder_phase_acc_0_we1_local = 1'b1;
    end else begin
        p_ZL17encoder_phase_acc_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL17encoder_phase_acc_1_address1_local = p_ZL17encoder_phase_acc_1_addr_reg_429_pp0_iter1_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL17encoder_phase_acc_1_address1_local = p_ZL17encoder_phase_acc_1_addr_reg_429;
        end else begin
            p_ZL17encoder_phase_acc_1_address1_local = 'bx;
        end
    end else begin
        p_ZL17encoder_phase_acc_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17encoder_phase_acc_1_ce0_local = 1'b1;
    end else begin
        p_ZL17encoder_phase_acc_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL17encoder_phase_acc_1_ce1_local = 1'b1;
    end else begin
        p_ZL17encoder_phase_acc_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL17encoder_phase_acc_1_d1_local = sub_ln79_reg_454;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL17encoder_phase_acc_1_d1_local = select_ln72_fu_301_p3;
        end else begin
            p_ZL17encoder_phase_acc_1_d1_local = 'bx;
        end
    end else begin
        p_ZL17encoder_phase_acc_1_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln93_reg_435 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln93_reg_435 == 1'd1)))) begin
        p_ZL17encoder_phase_acc_1_we1_local = 1'b1;
    end else begin
        p_ZL17encoder_phase_acc_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_fu_342_p2 = (encoder_spike_counter_loc_3_out_i + 32'd1);

assign add_ln69_fu_287_p2 = (select_ln69_fu_279_p3 + zext_ln68_fu_275_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage1_iter1_grp1 = ((ap_predicate_op71_write_state4 == 1'b1) & (encoder_spikes_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

always @ (*) begin
    ap_predicate_op71_write_state4 = ((tmp_1_reg_450 == 1'd1) & (icmp_ln77_reg_446 == 1'd0) & (icmp_ln99_reg_395 == 1'd1) & (icmp_ln95_reg_409_pp0_iter1_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign ch_2_fu_225_p2 = (ap_sig_allocacmp_ch_1 + 10'd1);

assign encoder_spike_counter_flag_3_out = 1'd1;

assign encoder_spike_counter_new_3_out = (encoder_spike_counter_loc_3_out_i + 32'd1);

assign encoder_spikes_din = $signed(or_ln54_3_fu_327_p5);

assign icmp_ln72_fu_293_p2 = ((add_ln69_reg_439 > encoder_config_delta_decay) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_310_p2 = ((select_ln72_fu_301_p3 < encoder_config_delta_threshold) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_219_p2 = ((ap_sig_allocacmp_ch_1 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_253_p2 = ((zext_ln93_fu_231_p1 < encoder_config_num_channels) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_205_p2 = ((empty == 4'd1) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_235_p4 = {{ap_sig_allocacmp_ch_1[9:1]}};

assign or_ln54_3_fu_327_p5 = {{{{{{1'd1}, {time_r}}}, {encoder_config_default_weight}}}, {zext_ln48_fu_324_p1}};

assign p_ZL13encoder_frame_0_address0 = zext_ln93_1_fu_245_p1;

assign p_ZL13encoder_frame_0_ce0 = p_ZL13encoder_frame_0_ce0_local;

assign p_ZL13encoder_frame_1_address0 = zext_ln93_1_fu_245_p1;

assign p_ZL13encoder_frame_1_ce0 = p_ZL13encoder_frame_1_ce0_local;

assign p_ZL17encoder_phase_acc_0_address0 = zext_ln93_1_fu_245_p1;

assign p_ZL17encoder_phase_acc_0_address1 = p_ZL17encoder_phase_acc_0_address1_local;

assign p_ZL17encoder_phase_acc_0_ce0 = p_ZL17encoder_phase_acc_0_ce0_local;

assign p_ZL17encoder_phase_acc_0_ce1 = p_ZL17encoder_phase_acc_0_ce1_local;

assign p_ZL17encoder_phase_acc_0_d1 = p_ZL17encoder_phase_acc_0_d1_local;

assign p_ZL17encoder_phase_acc_0_we1 = p_ZL17encoder_phase_acc_0_we1_local;

assign p_ZL17encoder_phase_acc_1_address0 = zext_ln93_1_fu_245_p1;

assign p_ZL17encoder_phase_acc_1_address1 = p_ZL17encoder_phase_acc_1_address1_local;

assign p_ZL17encoder_phase_acc_1_ce0 = p_ZL17encoder_phase_acc_1_ce0_local;

assign p_ZL17encoder_phase_acc_1_ce1 = p_ZL17encoder_phase_acc_1_ce1_local;

assign p_ZL17encoder_phase_acc_1_d1 = p_ZL17encoder_phase_acc_1_d1_local;

assign p_ZL17encoder_phase_acc_1_we1 = p_ZL17encoder_phase_acc_1_we1_local;

assign select_ln69_fu_279_p3 = ((trunc_ln93_fu_264_p1[0:0] == 1'b1) ? p_ZL17encoder_phase_acc_1_q0 : p_ZL17encoder_phase_acc_0_q0);

assign select_ln72_fu_301_p3 = ((icmp_ln72_fu_293_p2[0:0] == 1'b1) ? sub_ln73_fu_297_p2 : add_ln69_reg_439);

assign sub_ln73_fu_297_p2 = (add_ln69_reg_439 - encoder_config_delta_decay);

assign sub_ln79_fu_315_p2 = (select_ln72_fu_301_p3 - encoder_config_delta_threshold);

assign trunc_ln93_fu_264_p1 = ch_1_reg_399[0:0];

assign value_fu_267_p3 = ((trunc_ln93_fu_264_p1[0:0] == 1'b1) ? p_ZL13encoder_frame_1_q0 : p_ZL13encoder_frame_0_q0);

assign zext_ln48_fu_324_p1 = ch_1_reg_399_pp0_iter1_reg;

assign zext_ln68_fu_275_p1 = value_fu_267_p3;

assign zext_ln93_1_fu_245_p1 = lshr_ln1_fu_235_p4;

assign zext_ln93_fu_231_p1 = ap_sig_allocacmp_ch_1;

endmodule //snn_top_hls_snn_top_hls_Pipeline_ENCODER_LOOP
