// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_decay_all_traces (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        params_trace_decay_val,
        pre_traces_address0,
        pre_traces_ce0,
        pre_traces_q0,
        pre_traces_address1,
        pre_traces_ce1,
        pre_traces_we1,
        pre_traces_d1,
        post_traces_address0,
        post_traces_ce0,
        post_traces_q0,
        post_traces_address1,
        post_traces_ce1,
        post_traces_we1,
        post_traces_d1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] params_trace_decay_val;
output  [12:0] pre_traces_address0;
output   pre_traces_ce0;
input  [7:0] pre_traces_q0;
output  [12:0] pre_traces_address1;
output   pre_traces_ce1;
output   pre_traces_we1;
output  [7:0] pre_traces_d1;
output  [12:0] post_traces_address0;
output   post_traces_ce0;
input  [7:0] post_traces_q0;
output  [12:0] post_traces_address1;
output   post_traces_ce1;
output   post_traces_we1;
output  [7:0] post_traces_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_done;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_idle;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_ready;
wire   [12:0] grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_address0;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_ce0;
wire   [12:0] grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_address1;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_ce1;
wire    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_we1;
wire   [7:0] grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_d1;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_done;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_idle;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_ready;
wire   [12:0] grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_address0;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_ce0;
wire   [12:0] grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_address1;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_ce1;
wire    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_we1;
wire   [7:0] grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_d1;
reg    grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start_reg = 1'b0;
#0 grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start_reg = 1'b0;
end

snn_top_hls_decay_all_traces_Pipeline_DECAY_PRE_TRACE grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start),
    .ap_done(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_done),
    .ap_idle(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_idle),
    .ap_ready(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_ready),
    .zext_ln209(params_trace_decay_val),
    .pre_traces_address0(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_address0),
    .pre_traces_ce0(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_ce0),
    .pre_traces_q0(pre_traces_q0),
    .pre_traces_address1(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_address1),
    .pre_traces_ce1(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_ce1),
    .pre_traces_we1(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_we1),
    .pre_traces_d1(grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_d1)
);

snn_top_hls_decay_all_traces_Pipeline_DECAY_POST_TRACE grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start),
    .ap_done(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_done),
    .ap_idle(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_idle),
    .ap_ready(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_ready),
    .zext_ln209(params_trace_decay_val),
    .post_traces_address0(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_address0),
    .post_traces_ce0(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_ce0),
    .post_traces_q0(post_traces_q0),
    .post_traces_address1(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_address1),
    .post_traces_ce1(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_ce1),
    .post_traces_we1(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_we1),
    .post_traces_d1(grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start_reg <= 1'b1;
        end else if ((grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_ready == 1'b1)) begin
            grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start_reg <= 1'b1;
        end else if ((grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_ready == 1'b1)) begin
            grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_done == 1'b0) | (grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_done == 1'b0));
end

assign grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_ap_start_reg;

assign grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_ap_start_reg;

assign post_traces_address0 = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_address0;

assign post_traces_address1 = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_address1;

assign post_traces_ce0 = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_ce0;

assign post_traces_ce1 = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_ce1;

assign post_traces_d1 = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_d1;

assign post_traces_we1 = grp_decay_all_traces_Pipeline_DECAY_POST_TRACE_fu_36_post_traces_we1;

assign pre_traces_address0 = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_address0;

assign pre_traces_address1 = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_address1;

assign pre_traces_ce0 = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_ce0;

assign pre_traces_ce1 = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_ce1;

assign pre_traces_d1 = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_d1;

assign pre_traces_we1 = grp_decay_all_traces_Pipeline_DECAY_PRE_TRACE_fu_28_pre_traces_we1;

endmodule //snn_top_hls_decay_all_traces
