// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_LOAD_FRAME (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_data_TVALID,
        s_axis_data_TDATA,
        s_axis_data_TREADY,
        s_axis_data_TKEEP,
        s_axis_data_TSTRB,
        s_axis_data_TUSER,
        s_axis_data_TLAST,
        s_axis_data_TID,
        s_axis_data_TDEST,
        p_ZL13encoder_frame_0_address0,
        p_ZL13encoder_frame_0_ce0,
        p_ZL13encoder_frame_0_we0,
        p_ZL13encoder_frame_0_d0,
        p_ZL13encoder_frame_0_address1,
        p_ZL13encoder_frame_0_ce1,
        p_ZL13encoder_frame_0_we1,
        p_ZL13encoder_frame_0_d1,
        p_ZL13encoder_frame_1_address0,
        p_ZL13encoder_frame_1_ce0,
        p_ZL13encoder_frame_1_we0,
        p_ZL13encoder_frame_1_d0,
        p_ZL13encoder_frame_1_address1,
        p_ZL13encoder_frame_1_ce1,
        p_ZL13encoder_frame_1_we1,
        p_ZL13encoder_frame_1_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_data_TVALID;
input  [31:0] s_axis_data_TDATA;
output   s_axis_data_TREADY;
input  [3:0] s_axis_data_TKEEP;
input  [3:0] s_axis_data_TSTRB;
input  [0:0] s_axis_data_TUSER;
input  [0:0] s_axis_data_TLAST;
input  [0:0] s_axis_data_TID;
input  [0:0] s_axis_data_TDEST;
output  [8:0] p_ZL13encoder_frame_0_address0;
output   p_ZL13encoder_frame_0_ce0;
output   p_ZL13encoder_frame_0_we0;
output  [7:0] p_ZL13encoder_frame_0_d0;
output  [8:0] p_ZL13encoder_frame_0_address1;
output   p_ZL13encoder_frame_0_ce1;
output   p_ZL13encoder_frame_0_we1;
output  [7:0] p_ZL13encoder_frame_0_d1;
output  [8:0] p_ZL13encoder_frame_1_address0;
output   p_ZL13encoder_frame_1_ce0;
output   p_ZL13encoder_frame_1_we0;
output  [7:0] p_ZL13encoder_frame_1_d0;
output  [8:0] p_ZL13encoder_frame_1_address1;
output   p_ZL13encoder_frame_1_ce1;
output   p_ZL13encoder_frame_1_we1;
output  [7:0] p_ZL13encoder_frame_1_d1;

reg ap_idle;
reg s_axis_data_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_5_nbreadreq_fu_78_p9;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] or_cond75_fu_260_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_axis_data_TDATA_blk_n;
wire   [63:0] zext_ln863_fu_196_p1;
wire   [63:0] zext_ln865_fu_224_p1;
reg   [7:0] i_3_fu_74;
wire   [7:0] add_ln858_fu_174_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i;
reg    p_ZL13encoder_frame_0_we1_local;
wire   [7:0] trunc_ln863_fu_202_p1;
reg    p_ZL13encoder_frame_0_ce1_local;
reg    p_ZL13encoder_frame_0_we0_local;
reg    p_ZL13encoder_frame_0_ce0_local;
reg    p_ZL13encoder_frame_1_we1_local;
reg    p_ZL13encoder_frame_1_ce1_local;
reg    p_ZL13encoder_frame_1_we0_local;
reg    p_ZL13encoder_frame_1_ce0_local;
wire   [8:0] shl_ln_fu_188_p3;
wire   [8:0] or_ln_fu_216_p3;
wire   [0:0] icmp_ln858_fu_254_p2;
wire   [0:0] xor_ln867_fu_248_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_3_fu_74 = 8'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((tmp_5_nbreadreq_fu_78_p9 == 1'd1)) begin
            i_3_fu_74 <= add_ln858_fu_174_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_3_fu_74 <= 8'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & ((or_cond75_fu_260_p2 == 1'd0) | (tmp_5_nbreadreq_fu_78_p9 == 1'd0)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i = 8'd0;
    end else begin
        ap_sig_allocacmp_i = i_3_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_0_ce0_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_0_ce1_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_0_we0_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_0_we1_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_1_ce0_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_1_ce1_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_1_we0_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL13encoder_frame_1_we1_local = 1'b1;
    end else begin
        p_ZL13encoder_frame_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_data_TDATA_blk_n = s_axis_data_TVALID;
    end else begin
        s_axis_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_data_TREADY = 1'b1;
    end else begin
        s_axis_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln858_fu_174_p2 = (ap_sig_allocacmp_i + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((tmp_5_nbreadreq_fu_78_p9 == 1'd1) & (s_axis_data_TVALID == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln858_fu_254_p2 = ((add_ln858_fu_174_p2 < 8'd196) ? 1'b1 : 1'b0);

assign or_cond75_fu_260_p2 = (xor_ln867_fu_248_p2 & icmp_ln858_fu_254_p2);

assign or_ln_fu_216_p3 = {{ap_sig_allocacmp_i}, {1'd1}};

assign p_ZL13encoder_frame_0_address0 = zext_ln865_fu_224_p1;

assign p_ZL13encoder_frame_0_address1 = zext_ln863_fu_196_p1;

assign p_ZL13encoder_frame_0_ce0 = p_ZL13encoder_frame_0_ce0_local;

assign p_ZL13encoder_frame_0_ce1 = p_ZL13encoder_frame_0_ce1_local;

assign p_ZL13encoder_frame_0_d0 = {{s_axis_data_TDATA[23:16]}};

assign p_ZL13encoder_frame_0_d1 = trunc_ln863_fu_202_p1;

assign p_ZL13encoder_frame_0_we0 = p_ZL13encoder_frame_0_we0_local;

assign p_ZL13encoder_frame_0_we1 = p_ZL13encoder_frame_0_we1_local;

assign p_ZL13encoder_frame_1_address0 = zext_ln865_fu_224_p1;

assign p_ZL13encoder_frame_1_address1 = zext_ln863_fu_196_p1;

assign p_ZL13encoder_frame_1_ce0 = p_ZL13encoder_frame_1_ce0_local;

assign p_ZL13encoder_frame_1_ce1 = p_ZL13encoder_frame_1_ce1_local;

assign p_ZL13encoder_frame_1_d0 = {{s_axis_data_TDATA[31:24]}};

assign p_ZL13encoder_frame_1_d1 = {{s_axis_data_TDATA[15:8]}};

assign p_ZL13encoder_frame_1_we0 = p_ZL13encoder_frame_1_we0_local;

assign p_ZL13encoder_frame_1_we1 = p_ZL13encoder_frame_1_we1_local;

assign shl_ln_fu_188_p3 = {{ap_sig_allocacmp_i}, {1'd0}};

assign tmp_5_nbreadreq_fu_78_p9 = s_axis_data_TVALID;

assign trunc_ln863_fu_202_p1 = s_axis_data_TDATA[7:0];

assign xor_ln867_fu_248_p2 = (s_axis_data_TLAST ^ 1'd1);

assign zext_ln863_fu_196_p1 = shl_ln_fu_188_p3;

assign zext_ln865_fu_224_p1 = or_ln_fu_216_p3;

endmodule //snn_top_hls_snn_top_hls_Pipeline_LOAD_FRAME
