// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_process_post_spike_aer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        post_id,
        params_a_plus_val,
        params_learning_rate_val,
        learn_weight_ready,
        post_traces_address0,
        post_traces_ce0,
        post_traces_q0,
        post_traces_address1,
        post_traces_ce1,
        post_traces_we1,
        post_traces_d1,
        CONNECTION_TABLE_src_size_address0,
        CONNECTION_TABLE_src_size_ce0,
        CONNECTION_TABLE_src_size_q0,
        pre_traces_address0,
        pre_traces_ce0,
        pre_traces_q0,
        weight_memory_address0,
        weight_memory_ce0,
        weight_memory_we0,
        weight_memory_d0,
        weight_memory_q0,
        learn_bridge_valid_i,
        learn_bridge_valid_o,
        learn_bridge_valid_o_ap_vld,
        learn_bridge_group,
        learn_bridge_group_ap_vld,
        learn_bridge_src,
        learn_bridge_src_ap_vld,
        learn_bridge_dst,
        learn_bridge_dst_ap_vld,
        learn_bridge_data,
        learn_bridge_data_ap_vld,
        learn_bridge_exc,
        learn_bridge_exc_ap_vld,
        learn_bridge_is_inter,
        learn_bridge_is_inter_ap_vld,
        learn_bridge_dst_group,
        learn_bridge_dst_group_ap_vld
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] post_id;
input  [15:0] params_a_plus_val;
input  [15:0] params_learning_rate_val;
input  [0:0] learn_weight_ready;
output  [12:0] post_traces_address0;
output   post_traces_ce0;
input  [7:0] post_traces_q0;
output  [12:0] post_traces_address1;
output   post_traces_ce1;
output   post_traces_we1;
output  [7:0] post_traces_d1;
output  [2:0] CONNECTION_TABLE_src_size_address0;
output   CONNECTION_TABLE_src_size_ce0;
input  [10:0] CONNECTION_TABLE_src_size_q0;
output  [12:0] pre_traces_address0;
output   pre_traces_ce0;
input  [7:0] pre_traces_q0;
output  [19:0] weight_memory_address0;
output   weight_memory_ce0;
output   weight_memory_we0;
output  [3:0] weight_memory_d0;
input  [3:0] weight_memory_q0;
input  [0:0] learn_bridge_valid_i;
output  [0:0] learn_bridge_valid_o;
output   learn_bridge_valid_o_ap_vld;
output  [3:0] learn_bridge_group;
output   learn_bridge_group_ap_vld;
output  [6:0] learn_bridge_src;
output   learn_bridge_src_ap_vld;
output  [6:0] learn_bridge_dst;
output   learn_bridge_dst_ap_vld;
output  [3:0] learn_bridge_data;
output   learn_bridge_data_ap_vld;
output  [0:0] learn_bridge_exc;
output   learn_bridge_exc_ap_vld;
output  [0:0] learn_bridge_is_inter;
output   learn_bridge_is_inter_ap_vld;
output  [3:0] learn_bridge_dst_group;
output   learn_bridge_dst_group_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] learn_bridge_valid_o;
reg[3:0] learn_bridge_group;
reg[6:0] learn_bridge_src;
reg[6:0] learn_bridge_dst;
reg[3:0] learn_bridge_data;
reg[0:0] learn_bridge_exc;
reg[0:0] learn_bridge_is_inter;
reg[3:0] learn_bridge_dst_group;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] CONNECTION_TABLE_dst_id_start_address0;
wire   [12:0] CONNECTION_TABLE_dst_id_start_q0;
wire   [2:0] CONNECTION_TABLE_dst_size_address0;
wire   [10:0] CONNECTION_TABLE_dst_size_q0;
wire   [2:0] CONNECTION_TABLE_weight_offset_address0;
wire   [19:0] CONNECTION_TABLE_weight_offset_q0;
wire   [2:0] CONNECTION_TABLE_src_id_start_address0;
wire   [11:0] CONNECTION_TABLE_src_id_start_q0;
wire   [6:0] empty_fu_239_p1;
reg   [6:0] empty_reg_391;
reg   [12:0] post_traces_addr_reg_396;
reg   [3:0] dst_group_reg_402;
reg   [7:0] post_traces_load_reg_407;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [11:0] zext_ln381_fu_293_p1;
reg   [11:0] zext_ln381_reg_427;
wire   [12:0] zext_ln381_1_fu_296_p1;
reg   [12:0] zext_ln381_1_reg_432;
wire   [3:0] add_ln341_fu_308_p2;
reg   [3:0] add_ln341_reg_441;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln341_fu_314_p1;
reg   [63:0] zext_ln341_reg_446;
reg   [10:0] CONNECTION_TABLE_dst_size_load_reg_463;
wire    ap_CS_fsm_state5;
wire   [0:0] or_ln346_fu_350_p2;
reg   [0:0] or_ln346_reg_468;
wire   [11:0] local_dst_fu_356_p2;
reg   [11:0] local_dst_reg_477;
reg   [10:0] CONNECTION_TABLE_src_size_load_reg_492;
wire    ap_CS_fsm_state6;
wire   [20:0] widx_fu_368_p2;
reg   [20:0] widx_reg_497;
reg   [11:0] CONNECTION_TABLE_src_id_start_load_reg_502;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_done;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_idle;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_ready;
wire   [12:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_pre_traces_address0;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_pre_traces_ce0;
wire   [19:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_address0;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_ce0;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_we0;
wire   [3:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_d0;
wire   [0:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o_ap_vld;
wire   [3:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group_ap_vld;
wire   [6:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src_ap_vld;
wire   [6:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_ap_vld;
wire   [3:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data_ap_vld;
wire   [0:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc_ap_vld;
wire   [0:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter_ap_vld;
wire   [3:0] grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group;
wire    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group_ap_vld;
reg    grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [0:0] learn_bridge_valid_o_reg;
reg   [3:0] learn_bridge_group_reg;
reg   [6:0] learn_bridge_src_reg;
reg   [6:0] learn_bridge_dst_reg;
reg   [3:0] learn_bridge_data_reg;
reg   [0:0] learn_bridge_exc_reg;
reg   [0:0] learn_bridge_is_inter_reg;
reg   [3:0] learn_bridge_dst_group_reg;
wire   [63:0] zext_ln332_fu_243_p1;
wire   [0:0] icmp_ln341_fu_302_p2;
reg   [3:0] c_fu_96;
reg    ap_block_state8_on_subcall_done;
reg    post_traces_ce0_local;
reg    post_traces_we1_local;
wire   [7:0] select_ln333_fu_284_p3;
reg    post_traces_ce1_local;
reg    CONNECTION_TABLE_dst_id_start_ce0_local;
reg    CONNECTION_TABLE_dst_size_ce0_local;
reg    CONNECTION_TABLE_src_size_ce0_local;
reg    CONNECTION_TABLE_weight_offset_ce0_local;
reg    CONNECTION_TABLE_src_id_start_ce0_local;
wire   [8:0] zext_ln332_1_fu_263_p1;
wire   [8:0] new_trace_fu_266_p2;
wire   [0:0] tmp_fu_272_p3;
wire   [7:0] trunc_ln333_fu_280_p1;
wire   [12:0] zext_ln345_fu_324_p1;
wire   [12:0] dst_end_fu_328_p2;
wire   [0:0] icmp_ln346_1_fu_339_p2;
wire   [0:0] icmp_ln346_fu_334_p2;
wire   [0:0] xor_ln346_fu_344_p2;
wire   [11:0] trunc_ln344_fu_320_p1;
wire   [20:0] zext_ln350_fu_364_p1;
wire  signed [20:0] sext_ln349_fu_361_p1;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start_reg = 1'b0;
#0 c_fu_96 = 4'd0;
end

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_dst_id_start_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_dst_id_start_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_dst_id_start_address0),
    .ce0(CONNECTION_TABLE_dst_id_start_ce0_local),
    .q0(CONNECTION_TABLE_dst_id_start_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_dst_size_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_dst_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_dst_size_address0),
    .ce0(CONNECTION_TABLE_dst_size_ce0_local),
    .q0(CONNECTION_TABLE_dst_size_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_weight_offset_ROM_AUTO_1R #(
    .DataWidth( 20 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_weight_offset_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_weight_offset_address0),
    .ce0(CONNECTION_TABLE_weight_offset_ce0_local),
    .q0(CONNECTION_TABLE_weight_offset_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_src_id_start_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_src_id_start_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_src_id_start_address0),
    .ce0(CONNECTION_TABLE_src_id_start_ce0_local),
    .q0(CONNECTION_TABLE_src_id_start_q0)
);

snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start),
    .ap_done(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_done),
    .ap_idle(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_idle),
    .ap_ready(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_ready),
    .sext_ln352(widx_reg_497),
    .CONNECTION_TABLE_src_size_load(CONNECTION_TABLE_src_size_load_reg_492),
    .zext_ln352_1(CONNECTION_TABLE_dst_size_load_reg_463),
    .zext_ln352(CONNECTION_TABLE_src_id_start_load_reg_502),
    .sext_ln381(params_a_plus_val),
    .sext_ln174(params_learning_rate_val),
    .learn_weight_ready(learn_weight_ready),
    .post_id(empty_reg_391),
    .dst_group(dst_group_reg_402),
    .pre_traces_address0(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_pre_traces_address0),
    .pre_traces_ce0(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_pre_traces_ce0),
    .pre_traces_q0(pre_traces_q0),
    .weight_memory_address0(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_address0),
    .weight_memory_ce0(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_ce0),
    .weight_memory_we0(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_we0),
    .weight_memory_d0(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_d0),
    .weight_memory_q0(weight_memory_q0),
    .learn_bridge_valid_i(learn_bridge_valid_i),
    .learn_bridge_valid_o(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o),
    .learn_bridge_valid_o_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o_ap_vld),
    .learn_bridge_group(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group),
    .learn_bridge_group_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group_ap_vld),
    .learn_bridge_src(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src),
    .learn_bridge_src_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src_ap_vld),
    .learn_bridge_dst(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst),
    .learn_bridge_dst_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_ap_vld),
    .learn_bridge_data(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data),
    .learn_bridge_data_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data_ap_vld),
    .learn_bridge_exc(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc),
    .learn_bridge_exc_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc_ap_vld),
    .learn_bridge_is_inter(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter),
    .learn_bridge_is_inter_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter_ap_vld),
    .learn_bridge_dst_group(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group),
    .learn_bridge_dst_group_ap_vld(grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start_reg <= 1'b1;
        end else if ((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_ready == 1'b1)) begin
            grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_fu_96 <= 4'd0;
    end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        c_fu_96 <= add_ln341_reg_441;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_dst_size_load_reg_463 <= CONNECTION_TABLE_dst_size_q0;
        local_dst_reg_477 <= local_dst_fu_356_p2;
        or_ln346_reg_468 <= or_ln346_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        CONNECTION_TABLE_src_id_start_load_reg_502 <= CONNECTION_TABLE_src_id_start_q0;
        CONNECTION_TABLE_src_size_load_reg_492 <= CONNECTION_TABLE_src_size_q0;
        widx_reg_497 <= widx_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln341_reg_441 <= add_ln341_fu_308_p2;
        zext_ln341_reg_446[3 : 0] <= zext_ln341_fu_314_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        dst_group_reg_402 <= {{post_id[10:7]}};
        empty_reg_391 <= empty_fu_239_p1;
        post_traces_addr_reg_396[10 : 0] <= zext_ln332_fu_243_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_data_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_dst_group_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_dst_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_exc_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_group_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_is_inter_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_src_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_valid_o_reg <= grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        post_traces_load_reg_407 <= post_traces_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln381_1_reg_432[10 : 0] <= zext_ln381_1_fu_296_p1[10 : 0];
        zext_ln381_reg_427[10 : 0] <= zext_ln381_fu_293_p1[10 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        CONNECTION_TABLE_dst_id_start_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_dst_id_start_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        CONNECTION_TABLE_dst_size_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_dst_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_src_id_start_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_src_id_start_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_src_size_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_src_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_weight_offset_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_weight_offset_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln341_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln341_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_data = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data;
    end else begin
        learn_bridge_data = learn_bridge_data_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_dst = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst;
    end else begin
        learn_bridge_dst = learn_bridge_dst_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_dst_group = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group;
    end else begin
        learn_bridge_dst_group = learn_bridge_dst_group_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_exc = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc;
    end else begin
        learn_bridge_exc = learn_bridge_exc_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_group = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group;
    end else begin
        learn_bridge_group = learn_bridge_group_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_is_inter = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter;
    end else begin
        learn_bridge_is_inter = learn_bridge_is_inter_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_src = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src;
    end else begin
        learn_bridge_src = learn_bridge_src_reg;
    end
end

always @ (*) begin
    if (((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8) & (or_ln346_reg_468 == 1'd0))) begin
        learn_bridge_valid_o = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o;
    end else begin
        learn_bridge_valid_o = learn_bridge_valid_o_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        post_traces_ce0_local = 1'b1;
    end else begin
        post_traces_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        post_traces_ce1_local = 1'b1;
    end else begin
        post_traces_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        post_traces_we1_local = 1'b1;
    end else begin
        post_traces_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln341_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (or_ln346_fu_350_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CONNECTION_TABLE_dst_id_start_address0 = zext_ln341_fu_314_p1;

assign CONNECTION_TABLE_dst_size_address0 = zext_ln341_fu_314_p1;

assign CONNECTION_TABLE_src_id_start_address0 = zext_ln341_reg_446;

assign CONNECTION_TABLE_src_size_address0 = zext_ln341_reg_446;

assign CONNECTION_TABLE_src_size_ce0 = CONNECTION_TABLE_src_size_ce0_local;

assign CONNECTION_TABLE_weight_offset_address0 = zext_ln341_reg_446;

assign add_ln341_fu_308_p2 = (c_fu_96 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_done == 1'b0) & (or_ln346_reg_468 == 1'd0));
end

assign dst_end_fu_328_p2 = (zext_ln345_fu_324_p1 + CONNECTION_TABLE_dst_id_start_q0);

assign empty_fu_239_p1 = post_id[6:0];

assign grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_ap_start_reg;

assign icmp_ln341_fu_302_p2 = ((c_fu_96 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln346_1_fu_339_p2 = ((zext_ln381_1_reg_432 < dst_end_fu_328_p2) ? 1'b1 : 1'b0);

assign icmp_ln346_fu_334_p2 = ((CONNECTION_TABLE_dst_id_start_q0 > zext_ln381_1_reg_432) ? 1'b1 : 1'b0);

assign learn_bridge_data_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_data_ap_vld;

assign learn_bridge_dst_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_ap_vld;

assign learn_bridge_dst_group_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_dst_group_ap_vld;

assign learn_bridge_exc_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_exc_ap_vld;

assign learn_bridge_group_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_group_ap_vld;

assign learn_bridge_is_inter_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_is_inter_ap_vld;

assign learn_bridge_src_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_src_ap_vld;

assign learn_bridge_valid_o_ap_vld = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_learn_bridge_valid_o_ap_vld;

assign local_dst_fu_356_p2 = (zext_ln381_reg_427 - trunc_ln344_fu_320_p1);

assign new_trace_fu_266_p2 = (zext_ln332_1_fu_263_p1 + 9'd128);

assign or_ln346_fu_350_p2 = (xor_ln346_fu_344_p2 | icmp_ln346_fu_334_p2);

assign post_traces_address0 = zext_ln332_fu_243_p1;

assign post_traces_address1 = post_traces_addr_reg_396;

assign post_traces_ce0 = post_traces_ce0_local;

assign post_traces_ce1 = post_traces_ce1_local;

assign post_traces_d1 = select_ln333_fu_284_p3;

assign post_traces_we1 = post_traces_we1_local;

assign pre_traces_address0 = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_pre_traces_address0;

assign pre_traces_ce0 = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_pre_traces_ce0;

assign select_ln333_fu_284_p3 = ((tmp_fu_272_p3[0:0] == 1'b1) ? 8'd255 : trunc_ln333_fu_280_p1);

assign sext_ln349_fu_361_p1 = $signed(local_dst_reg_477);

assign tmp_fu_272_p3 = new_trace_fu_266_p2[32'd8];

assign trunc_ln333_fu_280_p1 = new_trace_fu_266_p2[7:0];

assign trunc_ln344_fu_320_p1 = CONNECTION_TABLE_dst_id_start_q0[11:0];

assign weight_memory_address0 = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_address0;

assign weight_memory_ce0 = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_ce0;

assign weight_memory_d0 = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_d0;

assign weight_memory_we0 = grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_206_weight_memory_we0;

assign widx_fu_368_p2 = ($signed(zext_ln350_fu_364_p1) + $signed(sext_ln349_fu_361_p1));

assign xor_ln346_fu_344_p2 = (icmp_ln346_1_fu_339_p2 ^ 1'd1);

assign zext_ln332_1_fu_263_p1 = post_traces_load_reg_407;

assign zext_ln332_fu_243_p1 = post_id;

assign zext_ln341_fu_314_p1 = c_fu_96;

assign zext_ln345_fu_324_p1 = CONNECTION_TABLE_dst_size_q0;

assign zext_ln350_fu_364_p1 = CONNECTION_TABLE_weight_offset_q0;

assign zext_ln381_1_fu_296_p1 = post_id;

assign zext_ln381_fu_293_p1 = post_id;

always @ (posedge ap_clk) begin
    post_traces_addr_reg_396[12:11] <= 2'b00;
    zext_ln381_reg_427[11] <= 1'b0;
    zext_ln381_1_reg_432[12:11] <= 2'b00;
    zext_ln341_reg_446[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //snn_top_hls_process_post_spike_aer
