# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chipwisperer/Documents/SNN/snn_accelerator_integration/snn_accelerator_integration.srcs/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3.xci
# IP: The module: 'design_1_axi_mem_intercon_imp_auto_us_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chipwisperer/Documents/SNN/snn_accelerator_integration/snn_accelerator_integration.gen/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mem_intercon_imp_auto_us_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/chipwisperer/Documents/SNN/snn_accelerator_integration/snn_accelerator_integration.gen/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mem_intercon_imp_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/chipwisperer/Documents/SNN/snn_accelerator_integration/snn_accelerator_integration.srcs/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3.xci
# IP: The module: 'design_1_axi_mem_intercon_imp_auto_us_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chipwisperer/Documents/SNN/snn_accelerator_integration/snn_accelerator_integration.gen/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mem_intercon_imp_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/chipwisperer/Documents/SNN/snn_accelerator_integration/snn_accelerator_integration.gen/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mem_intercon_imp_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
