// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_process_pre_spike_aer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pre_id,
        params_a_minus_val,
        params_learning_rate_val,
        learn_weight_ready,
        pre_traces_address0,
        pre_traces_ce0,
        pre_traces_q0,
        pre_traces_address1,
        pre_traces_ce1,
        pre_traces_we1,
        pre_traces_d1,
        CONNECTION_TABLE_src_size_address0,
        CONNECTION_TABLE_src_size_ce0,
        CONNECTION_TABLE_src_size_q0,
        post_traces_address0,
        post_traces_ce0,
        post_traces_q0,
        weight_memory_address0,
        weight_memory_ce0,
        weight_memory_we0,
        weight_memory_d0,
        weight_memory_address1,
        weight_memory_ce1,
        weight_memory_q1,
        learn_bridge_valid_i,
        learn_bridge_valid_o,
        learn_bridge_valid_o_ap_vld,
        learn_bridge_group,
        learn_bridge_group_ap_vld,
        learn_bridge_src,
        learn_bridge_src_ap_vld,
        learn_bridge_dst,
        learn_bridge_dst_ap_vld,
        learn_bridge_data,
        learn_bridge_data_ap_vld,
        learn_bridge_exc,
        learn_bridge_exc_ap_vld,
        learn_bridge_is_inter,
        learn_bridge_is_inter_ap_vld,
        learn_bridge_dst_group,
        learn_bridge_dst_group_ap_vld
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [12:0] pre_id;
input  [15:0] params_a_minus_val;
input  [15:0] params_learning_rate_val;
input  [0:0] learn_weight_ready;
output  [12:0] pre_traces_address0;
output   pre_traces_ce0;
input  [7:0] pre_traces_q0;
output  [12:0] pre_traces_address1;
output   pre_traces_ce1;
output   pre_traces_we1;
output  [7:0] pre_traces_d1;
output  [2:0] CONNECTION_TABLE_src_size_address0;
output   CONNECTION_TABLE_src_size_ce0;
input  [10:0] CONNECTION_TABLE_src_size_q0;
output  [12:0] post_traces_address0;
output   post_traces_ce0;
input  [7:0] post_traces_q0;
output  [19:0] weight_memory_address0;
output   weight_memory_ce0;
output   weight_memory_we0;
output  [3:0] weight_memory_d0;
output  [19:0] weight_memory_address1;
output   weight_memory_ce1;
input  [3:0] weight_memory_q1;
input  [0:0] learn_bridge_valid_i;
output  [0:0] learn_bridge_valid_o;
output   learn_bridge_valid_o_ap_vld;
output  [3:0] learn_bridge_group;
output   learn_bridge_group_ap_vld;
output  [6:0] learn_bridge_src;
output   learn_bridge_src_ap_vld;
output  [6:0] learn_bridge_dst;
output   learn_bridge_dst_ap_vld;
output  [3:0] learn_bridge_data;
output   learn_bridge_data_ap_vld;
output  [0:0] learn_bridge_exc;
output   learn_bridge_exc_ap_vld;
output  [0:0] learn_bridge_is_inter;
output   learn_bridge_is_inter_ap_vld;
output  [3:0] learn_bridge_dst_group;
output   learn_bridge_dst_group_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] learn_bridge_valid_o;
reg[3:0] learn_bridge_group;
reg[6:0] learn_bridge_src;
reg[6:0] learn_bridge_dst;
reg[3:0] learn_bridge_data;
reg[0:0] learn_bridge_exc;
reg[0:0] learn_bridge_is_inter;
reg[3:0] learn_bridge_dst_group;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] CONNECTION_TABLE_src_id_start_address0;
wire   [11:0] CONNECTION_TABLE_src_id_start_q0;
wire   [2:0] CONNECTION_TABLE_weight_offset_address0;
wire   [19:0] CONNECTION_TABLE_weight_offset_q0;
wire   [2:0] CONNECTION_TABLE_dst_size_address0;
wire   [10:0] CONNECTION_TABLE_dst_size_q0;
wire   [2:0] CONNECTION_TABLE_dst_id_start_address0;
wire   [12:0] CONNECTION_TABLE_dst_id_start_q0;
wire   [6:0] empty_fu_245_p1;
reg   [6:0] empty_reg_419;
reg   [12:0] pre_traces_addr_reg_424;
reg   [1:0] tmp_25_reg_430;
reg   [3:0] src_group_reg_435;
reg   [7:0] pre_traces_load_reg_440;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [13:0] zext_ln289_fu_309_p1;
reg   [13:0] zext_ln289_reg_460;
wire   [3:0] add_ln254_fu_321_p2;
reg   [3:0] add_ln254_reg_468;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln254_fu_327_p1;
reg   [63:0] zext_ln254_reg_473;
wire   [0:0] or_ln259_fu_367_p2;
reg   [0:0] or_ln259_reg_490;
wire    ap_CS_fsm_state5;
wire   [13:0] local_src_fu_373_p2;
reg  signed [13:0] local_src_reg_494;
wire    ap_CS_fsm_state6;
reg   [19:0] CONNECTION_TABLE_weight_offset_load_reg_519;
wire   [23:0] zext_ln262_1_fu_381_p1;
reg   [23:0] zext_ln262_1_reg_524;
reg   [12:0] CONNECTION_TABLE_dst_id_start_load_reg_530;
wire    ap_CS_fsm_state8;
wire   [23:0] grp_fu_396_p3;
reg   [23:0] base_offset_reg_540;
wire    ap_CS_fsm_state9;
(* use_dsp = "no" *) wire   [23:0] add_ln265_fu_388_p2;
reg   [23:0] add_ln265_reg_545;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_done;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_idle;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_ready;
wire   [12:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_post_traces_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_post_traces_ce0;
wire   [19:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_ce0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_we0;
wire   [3:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_d0;
wire   [19:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_address1;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_ce1;
wire   [0:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o_ap_vld;
wire   [3:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group_ap_vld;
wire   [6:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src_ap_vld;
wire   [6:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_ap_vld;
wire   [3:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data_ap_vld;
wire   [0:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc_ap_vld;
wire   [0:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter_ap_vld;
wire   [3:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group_ap_vld;
reg    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start_reg;
reg   [10:0] ap_NS_fsm;
wire    ap_NS_fsm_state10;
wire    ap_CS_fsm_state11;
reg   [0:0] learn_bridge_valid_o_reg;
reg   [3:0] learn_bridge_group_reg;
reg   [6:0] learn_bridge_src_reg;
reg   [6:0] learn_bridge_dst_reg;
reg   [3:0] learn_bridge_data_reg;
reg   [0:0] learn_bridge_exc_reg;
reg   [0:0] learn_bridge_is_inter_reg;
reg   [3:0] learn_bridge_dst_group_reg;
wire   [63:0] zext_ln245_fu_249_p1;
wire   [0:0] icmp_ln254_fu_315_p2;
reg   [3:0] c_fu_102;
reg    ap_block_state11_on_subcall_done;
reg    pre_traces_ce0_local;
reg    pre_traces_we1_local;
wire   [7:0] select_ln246_fu_300_p3;
reg    pre_traces_ce1_local;
reg    CONNECTION_TABLE_src_id_start_ce0_local;
reg    CONNECTION_TABLE_src_size_ce0_local;
reg    CONNECTION_TABLE_weight_offset_ce0_local;
reg    CONNECTION_TABLE_dst_size_ce0_local;
reg    CONNECTION_TABLE_dst_id_start_ce0_local;
wire   [8:0] zext_ln245_1_fu_279_p1;
wire   [8:0] new_trace_fu_282_p2;
wire   [0:0] tmp_fu_288_p3;
wire   [7:0] trunc_ln246_fu_296_p1;
wire   [12:0] zext_ln258_fu_341_p1;
wire   [12:0] zext_ln257_1_fu_337_p1;
wire   [12:0] src_end_fu_345_p2;
wire   [0:0] icmp_ln259_1_fu_356_p2;
wire   [0:0] icmp_ln259_fu_351_p2;
wire   [0:0] xor_ln259_fu_361_p2;
wire   [13:0] zext_ln257_fu_333_p1;
wire  signed [23:0] add_ln265_fu_388_p0;
wire   [10:0] grp_fu_396_p1;
wire   [19:0] grp_fu_396_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire   [23:0] grp_fu_396_p10;
wire   [23:0] grp_fu_396_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start_reg = 1'b0;
#0 c_fu_102 = 4'd0;
end

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_src_id_start_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_src_id_start_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_src_id_start_address0),
    .ce0(CONNECTION_TABLE_src_id_start_ce0_local),
    .q0(CONNECTION_TABLE_src_id_start_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_weight_offset_ROM_AUTO_1R #(
    .DataWidth( 20 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_weight_offset_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_weight_offset_address0),
    .ce0(CONNECTION_TABLE_weight_offset_ce0_local),
    .q0(CONNECTION_TABLE_weight_offset_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_dst_size_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_dst_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_dst_size_address0),
    .ce0(CONNECTION_TABLE_dst_size_ce0_local),
    .q0(CONNECTION_TABLE_dst_size_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_dst_id_start_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_dst_id_start_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_dst_id_start_address0),
    .ce0(CONNECTION_TABLE_dst_id_start_ce0_local),
    .q0(CONNECTION_TABLE_dst_id_start_q0)
);

snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start),
    .ap_done(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_done),
    .ap_idle(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_idle),
    .ap_ready(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_ready),
    .base_offset(base_offset_reg_540),
    .add_ln265_1(add_ln265_reg_545),
    .CONNECTION_TABLE_dst_id_start_load(CONNECTION_TABLE_dst_id_start_load_reg_530),
    .sext_ln294(params_a_minus_val),
    .sext_ln168(params_learning_rate_val),
    .learn_weight_ready(learn_weight_ready),
    .pre_id(empty_reg_419),
    .src_group(src_group_reg_435),
    .empty(tmp_25_reg_430),
    .post_traces_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_post_traces_address0),
    .post_traces_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_post_traces_ce0),
    .post_traces_q0(post_traces_q0),
    .weight_memory_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_address0),
    .weight_memory_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_ce0),
    .weight_memory_we0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_we0),
    .weight_memory_d0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_d0),
    .weight_memory_address1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_address1),
    .weight_memory_ce1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_ce1),
    .weight_memory_q1(weight_memory_q1),
    .learn_bridge_valid_i(learn_bridge_valid_i),
    .learn_bridge_valid_o(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o),
    .learn_bridge_valid_o_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o_ap_vld),
    .learn_bridge_group(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group),
    .learn_bridge_group_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group_ap_vld),
    .learn_bridge_src(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src),
    .learn_bridge_src_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src_ap_vld),
    .learn_bridge_dst(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst),
    .learn_bridge_dst_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_ap_vld),
    .learn_bridge_data(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data),
    .learn_bridge_data_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data_ap_vld),
    .learn_bridge_exc(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc),
    .learn_bridge_exc_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc_ap_vld),
    .learn_bridge_is_inter(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter),
    .learn_bridge_is_inter_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter_ap_vld),
    .learn_bridge_dst_group(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group),
    .learn_bridge_dst_group_ap_vld(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group_ap_vld)
);

snn_top_hls_mac_muladd_14s_11ns_20ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 24 ))
mac_muladd_14s_11ns_20ns_24_4_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(local_src_reg_494),
    .din1(grp_fu_396_p1),
    .din2(grp_fu_396_p2),
    .ce(1'b1),
    .dout(grp_fu_396_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state10) & (1'b1 == ap_CS_fsm_state9))) begin
            grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start_reg <= 1'b1;
        end else if ((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_ready == 1'b1)) begin
            grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_fu_102 <= 4'd0;
    end else if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        c_fu_102 <= add_ln254_reg_468;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        CONNECTION_TABLE_dst_id_start_load_reg_530 <= CONNECTION_TABLE_dst_id_start_q0;
        CONNECTION_TABLE_weight_offset_load_reg_519 <= CONNECTION_TABLE_weight_offset_q0;
        zext_ln262_1_reg_524[10 : 0] <= zext_ln262_1_fu_381_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln254_reg_468 <= add_ln254_fu_321_p2;
        zext_ln254_reg_473[3 : 0] <= zext_ln254_fu_327_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln265_reg_545 <= add_ln265_fu_388_p2;
        base_offset_reg_540 <= grp_fu_396_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_419 <= empty_fu_245_p1;
        pre_traces_addr_reg_424 <= zext_ln245_fu_249_p1;
        src_group_reg_435 <= {{pre_id[10:7]}};
        tmp_25_reg_430 <= {{pre_id[12:11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_data_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_dst_group_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_dst_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_exc_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_group_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_is_inter_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_src_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_valid_o_reg <= grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        local_src_reg_494 <= local_src_fu_373_p2;
        or_ln259_reg_490 <= or_ln259_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pre_traces_load_reg_440 <= pre_traces_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln289_reg_460[12 : 0] <= zext_ln289_fu_309_p1[12 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_dst_id_start_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_dst_id_start_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_dst_size_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_dst_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        CONNECTION_TABLE_src_id_start_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_src_id_start_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        CONNECTION_TABLE_src_size_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_src_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        CONNECTION_TABLE_weight_offset_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_weight_offset_ce0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln254_fu_315_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln254_fu_315_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_data = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data;
    end else begin
        learn_bridge_data = learn_bridge_data_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_dst = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst;
    end else begin
        learn_bridge_dst = learn_bridge_dst_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_dst_group = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group;
    end else begin
        learn_bridge_dst_group = learn_bridge_dst_group_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_exc = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc;
    end else begin
        learn_bridge_exc = learn_bridge_exc_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_group = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group;
    end else begin
        learn_bridge_group = learn_bridge_group_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_is_inter = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter;
    end else begin
        learn_bridge_is_inter = learn_bridge_is_inter_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_src = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src;
    end else begin
        learn_bridge_src = learn_bridge_src_reg;
    end
end

always @ (*) begin
    if (((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11) & (or_ln259_reg_490 == 1'd0))) begin
        learn_bridge_valid_o = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o;
    end else begin
        learn_bridge_valid_o = learn_bridge_valid_o_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pre_traces_ce0_local = 1'b1;
    end else begin
        pre_traces_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pre_traces_ce1_local = 1'b1;
    end else begin
        pre_traces_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pre_traces_we1_local = 1'b1;
    end else begin
        pre_traces_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln254_fu_315_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (or_ln259_fu_367_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CONNECTION_TABLE_dst_id_start_address0 = zext_ln254_reg_473;

assign CONNECTION_TABLE_dst_size_address0 = zext_ln254_reg_473;

assign CONNECTION_TABLE_src_id_start_address0 = zext_ln254_fu_327_p1;

assign CONNECTION_TABLE_src_size_address0 = zext_ln254_fu_327_p1;

assign CONNECTION_TABLE_src_size_ce0 = CONNECTION_TABLE_src_size_ce0_local;

assign CONNECTION_TABLE_weight_offset_address0 = zext_ln254_reg_473;

assign add_ln254_fu_321_p2 = (c_fu_102 + 4'd1);

assign add_ln265_fu_388_p0 = grp_fu_396_p3;

assign add_ln265_fu_388_p2 = ($signed(add_ln265_fu_388_p0) + $signed(zext_ln262_1_reg_524));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state10 = ap_NS_fsm[32'd9];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_done == 1'b0) & (or_ln259_reg_490 == 1'd0));
end

assign empty_fu_245_p1 = pre_id[6:0];

assign grp_fu_396_p1 = grp_fu_396_p10;

assign grp_fu_396_p10 = CONNECTION_TABLE_dst_size_q0;

assign grp_fu_396_p2 = grp_fu_396_p20;

assign grp_fu_396_p20 = CONNECTION_TABLE_weight_offset_load_reg_519;

assign grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_ap_start_reg;

assign icmp_ln254_fu_315_p2 = ((c_fu_102 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln259_1_fu_356_p2 = ((pre_id < src_end_fu_345_p2) ? 1'b1 : 1'b0);

assign icmp_ln259_fu_351_p2 = ((zext_ln257_1_fu_337_p1 > pre_id) ? 1'b1 : 1'b0);

assign learn_bridge_data_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_data_ap_vld;

assign learn_bridge_dst_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_ap_vld;

assign learn_bridge_dst_group_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_dst_group_ap_vld;

assign learn_bridge_exc_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_exc_ap_vld;

assign learn_bridge_group_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_group_ap_vld;

assign learn_bridge_is_inter_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_is_inter_ap_vld;

assign learn_bridge_src_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_src_ap_vld;

assign learn_bridge_valid_o_ap_vld = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_learn_bridge_valid_o_ap_vld;

assign local_src_fu_373_p2 = (zext_ln289_reg_460 - zext_ln257_fu_333_p1);

assign new_trace_fu_282_p2 = (zext_ln245_1_fu_279_p1 + 9'd128);

assign or_ln259_fu_367_p2 = (xor_ln259_fu_361_p2 | icmp_ln259_fu_351_p2);

assign post_traces_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_post_traces_address0;

assign post_traces_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_post_traces_ce0;

assign pre_traces_address0 = zext_ln245_fu_249_p1;

assign pre_traces_address1 = pre_traces_addr_reg_424;

assign pre_traces_ce0 = pre_traces_ce0_local;

assign pre_traces_ce1 = pre_traces_ce1_local;

assign pre_traces_d1 = select_ln246_fu_300_p3;

assign pre_traces_we1 = pre_traces_we1_local;

assign select_ln246_fu_300_p3 = ((tmp_fu_288_p3[0:0] == 1'b1) ? 8'd255 : trunc_ln246_fu_296_p1);

assign src_end_fu_345_p2 = (zext_ln258_fu_341_p1 + zext_ln257_1_fu_337_p1);

assign tmp_fu_288_p3 = new_trace_fu_282_p2[32'd8];

assign trunc_ln246_fu_296_p1 = new_trace_fu_282_p2[7:0];

assign weight_memory_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_address0;

assign weight_memory_address1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_address1;

assign weight_memory_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_ce0;

assign weight_memory_ce1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_ce1;

assign weight_memory_d0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_d0;

assign weight_memory_we0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_212_weight_memory_we0;

assign xor_ln259_fu_361_p2 = (icmp_ln259_1_fu_356_p2 ^ 1'd1);

assign zext_ln245_1_fu_279_p1 = pre_traces_load_reg_440;

assign zext_ln245_fu_249_p1 = pre_id;

assign zext_ln254_fu_327_p1 = c_fu_102;

assign zext_ln257_1_fu_337_p1 = CONNECTION_TABLE_src_id_start_q0;

assign zext_ln257_fu_333_p1 = CONNECTION_TABLE_src_id_start_q0;

assign zext_ln258_fu_341_p1 = CONNECTION_TABLE_src_size_q0;

assign zext_ln262_1_fu_381_p1 = CONNECTION_TABLE_dst_size_q0;

assign zext_ln289_fu_309_p1 = pre_id;

always @ (posedge ap_clk) begin
    zext_ln289_reg_460[13] <= 1'b0;
    zext_ln254_reg_473[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln262_1_reg_524[23:11] <= 13'b0000000000000;
end

endmodule //snn_top_hls_process_pre_spike_aer
