// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln352,
        CONNECTION_TABLE_src_size_load,
        zext_ln352_1,
        zext_ln352,
        sext_ln381,
        sext_ln174,
        learn_weight_ready,
        post_id,
        dst_group,
        pre_traces_address0,
        pre_traces_ce0,
        pre_traces_q0,
        weight_memory_address0,
        weight_memory_ce0,
        weight_memory_we0,
        weight_memory_d0,
        weight_memory_q0,
        learn_bridge_valid_i,
        learn_bridge_valid_o,
        learn_bridge_valid_o_ap_vld,
        learn_bridge_group,
        learn_bridge_group_ap_vld,
        learn_bridge_src,
        learn_bridge_src_ap_vld,
        learn_bridge_dst,
        learn_bridge_dst_ap_vld,
        learn_bridge_data,
        learn_bridge_data_ap_vld,
        learn_bridge_exc,
        learn_bridge_exc_ap_vld,
        learn_bridge_is_inter,
        learn_bridge_is_inter_ap_vld,
        learn_bridge_dst_group,
        learn_bridge_dst_group_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 12'd1;
parameter    ap_ST_fsm_pp0_stage1 = 12'd2;
parameter    ap_ST_fsm_pp0_stage2 = 12'd4;
parameter    ap_ST_fsm_pp0_stage3 = 12'd8;
parameter    ap_ST_fsm_pp0_stage4 = 12'd16;
parameter    ap_ST_fsm_pp0_stage5 = 12'd32;
parameter    ap_ST_fsm_pp0_stage6 = 12'd64;
parameter    ap_ST_fsm_pp0_stage7 = 12'd128;
parameter    ap_ST_fsm_pp0_stage8 = 12'd256;
parameter    ap_ST_fsm_pp0_stage9 = 12'd512;
parameter    ap_ST_fsm_pp0_stage10 = 12'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [20:0] sext_ln352;
input  [10:0] CONNECTION_TABLE_src_size_load;
input  [10:0] zext_ln352_1;
input  [11:0] zext_ln352;
input  [15:0] sext_ln381;
input  [15:0] sext_ln174;
input  [0:0] learn_weight_ready;
input  [6:0] post_id;
input  [3:0] dst_group;
output  [12:0] pre_traces_address0;
output   pre_traces_ce0;
input  [7:0] pre_traces_q0;
output  [19:0] weight_memory_address0;
output   weight_memory_ce0;
output   weight_memory_we0;
output  [3:0] weight_memory_d0;
input  [3:0] weight_memory_q0;
input  [0:0] learn_bridge_valid_i;
output  [0:0] learn_bridge_valid_o;
output   learn_bridge_valid_o_ap_vld;
output  [3:0] learn_bridge_group;
output   learn_bridge_group_ap_vld;
output  [6:0] learn_bridge_src;
output   learn_bridge_src_ap_vld;
output  [6:0] learn_bridge_dst;
output   learn_bridge_dst_ap_vld;
output  [3:0] learn_bridge_data;
output   learn_bridge_data_ap_vld;
output  [0:0] learn_bridge_exc;
output   learn_bridge_exc_ap_vld;
output  [0:0] learn_bridge_is_inter;
output   learn_bridge_is_inter_ap_vld;
output  [3:0] learn_bridge_dst_group;
output   learn_bridge_dst_group_ap_vld;

reg ap_idle;
reg[0:0] learn_bridge_valid_o;
reg learn_bridge_valid_o_ap_vld;
reg learn_bridge_group_ap_vld;
reg learn_bridge_src_ap_vld;
reg learn_bridge_dst_ap_vld;
reg learn_bridge_data_ap_vld;
reg learn_bridge_exc_ap_vld;
reg learn_bridge_is_inter_ap_vld;
reg learn_bridge_dst_group_ap_vld;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln352_reg_621;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage0_11001;
wire  signed [27:0] sext_ln381_cast_fu_244_p1;
reg  signed [27:0] sext_ln381_cast_reg_606;
wire   [21:0] zext_ln352_1_cast_fu_252_p1;
reg   [21:0] zext_ln352_1_cast_reg_611;
wire  signed [27:0] sext_ln174_cast_fu_260_p1;
reg  signed [27:0] sext_ln174_cast_reg_616;
wire   [0:0] icmp_ln352_fu_277_p2;
wire   [12:0] pre_id_fu_293_p2;
reg   [12:0] pre_id_reg_625;
reg   [7:0] pre_trace_val_reg_637;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln363_fu_317_p2;
reg   [0:0] icmp_ln363_reg_642;
reg   [19:0] weight_memory_addr_reg_646;
wire   [0:0] or_ln168_fu_353_p2;
reg   [0:0] or_ln168_reg_651;
reg  signed [3:0] current_w_reg_655;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
wire   [3:0] updated_fu_529_p3;
reg   [3:0] updated_reg_680;
wire   [63:0] zext_ln359_fu_299_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln352_2_fu_312_p1;
wire    ap_block_pp0_stage1;
wire   [3:0] src_group_fu_359_p4;
reg   [10:0] ii_fu_156;
wire   [10:0] add_ln352_fu_283_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_ii_1;
reg   [21:0] widx_fu_160;
wire   [21:0] add_ln396_fu_413_p2;
wire  signed [21:0] sext_ln352_cast_fu_256_p1;
reg    pre_traces_ce0_local;
reg    weight_memory_ce0_local;
reg   [19:0] weight_memory_address0_local;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg    weight_memory_we0_local;
wire   [12:0] zext_ln352_3_fu_289_p1;
wire   [12:0] zext_ln352_cast_fu_248_p1;
wire   [0:0] xor_ln163_fu_327_p2;
wire   [1:0] tmp_26_fu_338_p4;
wire   [0:0] and_ln163_fu_332_p2;
wire   [0:0] icmp_ln168_fu_347_p2;
wire  signed [3:0] distance_fu_423_p1;
wire    ap_block_pp0_stage4;
wire   [3:0] distance_fu_423_p2;
wire   [3:0] grp_fu_436_p0;
wire   [7:0] grp_fu_436_p1;
wire   [11:0] grp_fu_436_p2;
wire    ap_block_pp0_stage6;
wire   [11:0] grp_fu_446_p0;
wire  signed [15:0] grp_fu_446_p1;
wire   [27:0] grp_fu_446_p2;
wire    ap_block_pp0_stage9;
wire  signed [11:0] trunc_ln_fu_451_p4;
wire  signed [15:0] grp_fu_465_p1;
wire   [27:0] grp_fu_465_p2;
wire   [15:0] delta_fu_473_p4;
wire  signed [15:0] sext_ln369_fu_470_p1;
wire   [15:0] w_fu_483_p2;
wire   [12:0] tmp_fu_489_p4;
wire   [0:0] icmp_ln131_fu_499_p2;
wire   [0:0] icmp_ln132_fu_505_p2;
wire   [0:0] or_ln131_fu_523_p2;
wire   [3:0] select_ln131_fu_515_p3;
wire   [3:0] trunc_ln133_fu_511_p1;
wire   [0:0] tmp_27_fu_538_p3;
wire   [3:0] mag_3_fu_551_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [11:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [11:0] grp_fu_436_p00;
wire   [11:0] grp_fu_436_p10;
wire   [27:0] grp_fu_446_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ii_fu_156 = 11'd0;
#0 widx_fu_160 = 22'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_mul_4ns_8ns_12_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 12 ))
mul_4ns_8ns_12_3_1_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_436_p0),
    .din1(grp_fu_436_p1),
    .ce(1'b1),
    .dout(grp_fu_436_p2)
);

snn_top_hls_mul_12ns_16s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12ns_16s_28_4_1_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_446_p0),
    .din1(grp_fu_446_p1),
    .ce(1'b1),
    .dout(grp_fu_446_p2)
);

snn_top_hls_mul_12s_16s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12s_16s_28_4_1_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln_fu_451_p4),
    .din1(grp_fu_465_p1),
    .ce(1'b1),
    .dout(grp_fu_465_p2)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage11_subdone) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln352_fu_277_p2 == 1'd0))) begin
            ii_fu_156 <= add_ln352_fu_283_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ii_fu_156 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        widx_fu_160 <= sext_ln352_cast_fu_256_p1;
    end else if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        widx_fu_160 <= add_ln396_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        current_w_reg_655 <= weight_memory_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln352_reg_621 <= icmp_ln352_fu_277_p2;
        pre_id_reg_625 <= pre_id_fu_293_p2;
        sext_ln174_cast_reg_616 <= sext_ln174_cast_fu_260_p1;
        sext_ln381_cast_reg_606 <= sext_ln381_cast_fu_244_p1;
        updated_reg_680 <= updated_fu_529_p3;
        zext_ln352_1_cast_reg_611[10 : 0] <= zext_ln352_1_cast_fu_252_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln363_reg_642 <= icmp_ln363_fu_317_p2;
        or_ln168_reg_651 <= or_ln168_fu_353_p2;
        pre_trace_val_reg_637 <= pre_traces_q0;
        weight_memory_addr_reg_646 <= zext_ln352_2_fu_312_p1;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_subdone) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ii_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_ii_1 = ii_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_reg_651 == 1'd0) & (icmp_ln363_reg_642 == 1'd0))) begin
        learn_bridge_data_ap_vld = 1'b1;
    end else begin
        learn_bridge_data_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_dst_ap_vld = 1'b1;
    end else begin
        learn_bridge_dst_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_dst_group_ap_vld = 1'b1;
    end else begin
        learn_bridge_dst_group_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_reg_651 == 1'd0) & (icmp_ln363_reg_642 == 1'd0))) begin
        learn_bridge_exc_ap_vld = 1'b1;
    end else begin
        learn_bridge_exc_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_group_ap_vld = 1'b1;
    end else begin
        learn_bridge_group_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_is_inter_ap_vld = 1'b1;
    end else begin
        learn_bridge_is_inter_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_src_ap_vld = 1'b1;
    end else begin
        learn_bridge_src_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_valid_o = 1'd1;
    end else begin
        learn_bridge_valid_o = learn_bridge_valid_i;
    end
end

always @ (*) begin
    if (((icmp_ln352_reg_621 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln168_fu_353_p2 == 1'd0) & (icmp_ln363_fu_317_p2 == 1'd0))) begin
        learn_bridge_valid_o_ap_vld = 1'b1;
    end else begin
        learn_bridge_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pre_traces_ce0_local = 1'b1;
    end else begin
        pre_traces_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_memory_address0_local = weight_memory_addr_reg_646;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_memory_address0_local = zext_ln352_2_fu_312_p1;
    end else begin
        weight_memory_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        weight_memory_ce0_local = 1'b1;
    end else begin
        weight_memory_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln363_reg_642 == 1'd0))) begin
        weight_memory_we0_local = 1'b1;
    end else begin
        weight_memory_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln352_fu_283_p2 = (ap_sig_allocacmp_ii_1 + 11'd1);

assign add_ln396_fu_413_p2 = (zext_ln352_1_cast_reg_611 + widx_fu_160);

assign and_ln163_fu_332_p2 = (xor_ln163_fu_327_p2 & learn_bridge_valid_i);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign delta_fu_473_p4 = {{grp_fu_465_p2[23:8]}};

assign distance_fu_423_p1 = weight_memory_q0;

assign distance_fu_423_p2 = ($signed(4'd7) - $signed(distance_fu_423_p1));

assign grp_fu_436_p0 = grp_fu_436_p00;

assign grp_fu_436_p00 = distance_fu_423_p2;

assign grp_fu_436_p1 = grp_fu_436_p10;

assign grp_fu_436_p10 = pre_trace_val_reg_637;

assign grp_fu_446_p0 = grp_fu_446_p00;

assign grp_fu_446_p00 = grp_fu_436_p2;

assign grp_fu_446_p1 = sext_ln381_cast_reg_606;

assign grp_fu_465_p1 = sext_ln174_cast_reg_616;

assign icmp_ln131_fu_499_p2 = (($signed(tmp_fu_489_p4) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_505_p2 = (($signed(w_fu_483_p2) < $signed(16'd65528)) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_347_p2 = ((tmp_26_fu_338_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln352_fu_277_p2 = ((ap_sig_allocacmp_ii_1 == CONNECTION_TABLE_src_size_load) ? 1'b1 : 1'b0);

assign icmp_ln363_fu_317_p2 = ((pre_traces_q0 == 8'd0) ? 1'b1 : 1'b0);

assign learn_bridge_data = ((tmp_27_fu_538_p3[0:0] == 1'b1) ? mag_3_fu_551_p2 : updated_reg_680);

assign learn_bridge_dst = post_id;

assign learn_bridge_dst_group = dst_group;

assign learn_bridge_exc = (tmp_27_fu_538_p3 ^ 1'd1);

assign learn_bridge_group = {{pre_id_reg_625[10:7]}};

assign learn_bridge_is_inter = ((src_group_fu_359_p4 != dst_group) ? 1'b1 : 1'b0);

assign learn_bridge_src = pre_id_reg_625[6:0];

assign mag_3_fu_551_p2 = (4'd0 - updated_reg_680);

assign or_ln131_fu_523_p2 = (icmp_ln132_fu_505_p2 | icmp_ln131_fu_499_p2);

assign or_ln168_fu_353_p2 = (icmp_ln168_fu_347_p2 | and_ln163_fu_332_p2);

assign pre_id_fu_293_p2 = (zext_ln352_3_fu_289_p1 + zext_ln352_cast_fu_248_p1);

assign pre_traces_address0 = zext_ln359_fu_299_p1;

assign pre_traces_ce0 = pre_traces_ce0_local;

assign select_ln131_fu_515_p3 = ((icmp_ln131_fu_499_p2[0:0] == 1'b1) ? 4'd7 : 4'd8);

assign sext_ln174_cast_fu_260_p1 = $signed(sext_ln174);

assign sext_ln352_cast_fu_256_p1 = $signed(sext_ln352);

assign sext_ln369_fu_470_p1 = current_w_reg_655;

assign sext_ln381_cast_fu_244_p1 = $signed(sext_ln381);

assign src_group_fu_359_p4 = {{pre_id_reg_625[10:7]}};

assign tmp_26_fu_338_p4 = {{pre_id_reg_625[12:11]}};

assign tmp_27_fu_538_p3 = updated_reg_680[32'd3];

assign tmp_fu_489_p4 = {{w_fu_483_p2[15:3]}};

assign trunc_ln133_fu_511_p1 = w_fu_483_p2[3:0];

assign trunc_ln_fu_451_p4 = {{grp_fu_446_p2[27:16]}};

assign updated_fu_529_p3 = ((or_ln131_fu_523_p2[0:0] == 1'b1) ? select_ln131_fu_515_p3 : trunc_ln133_fu_511_p1);

assign w_fu_483_p2 = ($signed(delta_fu_473_p4) + $signed(sext_ln369_fu_470_p1));

assign weight_memory_address0 = weight_memory_address0_local;

assign weight_memory_ce0 = weight_memory_ce0_local;

assign weight_memory_d0 = updated_fu_529_p3;

assign weight_memory_we0 = weight_memory_we0_local;

assign xor_ln163_fu_327_p2 = (learn_weight_ready ^ 1'd1);

assign zext_ln352_1_cast_fu_252_p1 = zext_ln352_1;

assign zext_ln352_2_fu_312_p1 = widx_fu_160;

assign zext_ln352_3_fu_289_p1 = ap_sig_allocacmp_ii_1;

assign zext_ln352_cast_fu_248_p1 = zext_ln352;

assign zext_ln359_fu_299_p1 = pre_id_fu_293_p2;

always @ (posedge ap_clk) begin
    zext_ln352_1_cast_reg_611[21:11] <= 11'b00000000000;
end

endmodule //snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP
