// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_apply_rstdp_reward (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reward_signal,
        params_rstdp_enable_val,
        params_reward_scale_val,
        learn_weight_ready,
        CONNECTION_TABLE_src_size_address0,
        CONNECTION_TABLE_src_size_ce0,
        CONNECTION_TABLE_src_size_q0,
        pre_eligibility_address0,
        pre_eligibility_ce0,
        pre_eligibility_q0,
        post_eligibility_address0,
        post_eligibility_ce0,
        post_eligibility_q0,
        weight_memory_address0,
        weight_memory_ce0,
        weight_memory_we0,
        weight_memory_d0,
        weight_memory_address1,
        weight_memory_ce1,
        weight_memory_q1,
        learn_bridge_valid_i,
        learn_bridge_valid_o,
        learn_bridge_valid_o_ap_vld,
        learn_bridge_group,
        learn_bridge_group_ap_vld,
        learn_bridge_src,
        learn_bridge_src_ap_vld,
        learn_bridge_dst,
        learn_bridge_dst_ap_vld,
        learn_bridge_data,
        learn_bridge_data_ap_vld,
        learn_bridge_exc,
        learn_bridge_exc_ap_vld,
        learn_bridge_is_inter,
        learn_bridge_is_inter_ap_vld,
        learn_bridge_dst_group,
        learn_bridge_dst_group_ap_vld
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] reward_signal;
input  [0:0] params_rstdp_enable_val;
input  [15:0] params_reward_scale_val;
input  [0:0] learn_weight_ready;
output  [2:0] CONNECTION_TABLE_src_size_address0;
output   CONNECTION_TABLE_src_size_ce0;
input  [10:0] CONNECTION_TABLE_src_size_q0;
output  [12:0] pre_eligibility_address0;
output   pre_eligibility_ce0;
input  [7:0] pre_eligibility_q0;
output  [12:0] post_eligibility_address0;
output   post_eligibility_ce0;
input  [7:0] post_eligibility_q0;
output  [19:0] weight_memory_address0;
output   weight_memory_ce0;
output   weight_memory_we0;
output  [3:0] weight_memory_d0;
output  [19:0] weight_memory_address1;
output   weight_memory_ce1;
input  [3:0] weight_memory_q1;
input  [0:0] learn_bridge_valid_i;
output  [0:0] learn_bridge_valid_o;
output   learn_bridge_valid_o_ap_vld;
output  [3:0] learn_bridge_group;
output   learn_bridge_group_ap_vld;
output  [6:0] learn_bridge_src;
output   learn_bridge_src_ap_vld;
output  [6:0] learn_bridge_dst;
output   learn_bridge_dst_ap_vld;
output  [3:0] learn_bridge_data;
output   learn_bridge_data_ap_vld;
output  [0:0] learn_bridge_exc;
output   learn_bridge_exc_ap_vld;
output  [0:0] learn_bridge_is_inter;
output   learn_bridge_is_inter_ap_vld;
output  [3:0] learn_bridge_dst_group;
output   learn_bridge_dst_group_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] learn_bridge_valid_o;
reg[3:0] learn_bridge_group;
reg[6:0] learn_bridge_src;
reg[6:0] learn_bridge_dst;
reg[3:0] learn_bridge_data;
reg[0:0] learn_bridge_exc;
reg[0:0] learn_bridge_is_inter;
reg[3:0] learn_bridge_dst_group;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] CONNECTION_TABLE_src_id_start_address0;
wire   [11:0] CONNECTION_TABLE_src_id_start_q0;
wire   [2:0] CONNECTION_TABLE_weight_offset_address0;
wire   [19:0] CONNECTION_TABLE_weight_offset_q0;
wire   [2:0] CONNECTION_TABLE_dst_size_address0;
wire   [10:0] CONNECTION_TABLE_dst_size_q0;
wire   [2:0] CONNECTION_TABLE_dst_id_start_address0;
wire   [12:0] CONNECTION_TABLE_dst_id_start_q0;
wire   [0:0] and_ln419_fu_305_p2;
reg   [0:0] and_ln419_reg_556;
wire   [0:0] tmp_fu_311_p3;
reg   [0:0] tmp_reg_567;
wire   [1:0] shift_sel_fu_409_p9;
reg   [1:0] shift_sel_reg_572;
wire   [3:0] add_ln436_fu_443_p2;
reg   [3:0] add_ln436_reg_580;
wire    ap_CS_fsm_state2;
reg   [10:0] CONNECTION_TABLE_src_size_load_reg_610;
wire    ap_CS_fsm_state3;
wire   [12:0] zext_ln448_fu_458_p1;
reg   [12:0] zext_ln448_reg_615;
wire   [20:0] zext_ln448_1_fu_462_p1;
reg   [20:0] zext_ln448_1_reg_620;
wire   [20:0] zext_ln455_fu_466_p1;
reg   [20:0] zext_ln455_reg_626;
reg   [12:0] CONNECTION_TABLE_dst_id_start_load_reg_632;
wire   [10:0] add_ln440_fu_475_p2;
reg   [10:0] add_ln440_reg_640;
wire    ap_CS_fsm_state4;
wire   [12:0] add_ln485_fu_485_p2;
reg   [12:0] add_ln485_reg_645;
wire   [6:0] trunc_ln445_fu_490_p1;
reg   [6:0] trunc_ln445_reg_651;
wire   [20:0] add_ln440_1_fu_503_p2;
reg   [20:0] add_ln440_1_reg_661;
wire    ap_CS_fsm_state5;
reg   [7:0] pre_elig_reg_667;
wire   [0:0] icmp_ln446_fu_508_p2;
reg   [0:0] icmp_ln446_reg_672;
reg   [1:0] tmp_35_reg_676;
reg   [3:0] src_group_reg_681;
wire   [20:0] grp_fu_540_p3;
reg   [20:0] add_ln451_reg_691;
wire    ap_CS_fsm_state8;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_done;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_idle;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_ready;
wire   [12:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_post_eligibility_address0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_post_eligibility_ce0;
wire   [19:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_address0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_ce0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_we0;
wire   [3:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_d0;
wire   [19:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_address1;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_ce1;
wire   [0:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o_ap_vld;
wire   [3:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group_ap_vld;
wire   [6:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src_ap_vld;
wire   [6:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_ap_vld;
wire   [3:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data_ap_vld;
wire   [0:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc_ap_vld;
wire   [0:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter_ap_vld;
wire   [3:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group_ap_vld;
reg   [20:0] indvars_iv_reg_242;
wire    ap_CS_fsm_state10;
reg    ap_block_state10_on_subcall_done;
reg   [10:0] ii_reg_252;
reg    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [0:0] learn_bridge_valid_o_reg;
reg   [3:0] learn_bridge_group_reg;
reg   [6:0] learn_bridge_src_reg;
reg   [6:0] learn_bridge_dst_reg;
reg   [3:0] learn_bridge_data_reg;
reg   [0:0] learn_bridge_exc_reg;
reg   [0:0] learn_bridge_is_inter_reg;
reg   [3:0] learn_bridge_dst_group_reg;
wire   [63:0] zext_ln436_fu_449_p1;
wire   [0:0] icmp_ln436_fu_437_p2;
wire   [63:0] zext_ln445_fu_494_p1;
wire   [0:0] icmp_ln440_fu_470_p2;
reg   [3:0] c_fu_136;
reg    CONNECTION_TABLE_src_size_ce0_local;
reg    CONNECTION_TABLE_src_id_start_ce0_local;
reg    CONNECTION_TABLE_weight_offset_ce0_local;
reg    CONNECTION_TABLE_dst_size_ce0_local;
reg    CONNECTION_TABLE_dst_id_start_ce0_local;
reg    pre_eligibility_ce0_local;
wire   [0:0] icmp_ln419_fu_299_p2;
wire   [7:0] reward_mag_fu_319_p2;
wire   [7:0] reward_mag_1_fu_325_p3;
wire   [1:0] tmp_32_fu_333_p4;
wire   [2:0] tmp_33_fu_349_p4;
wire   [3:0] tmp_34_fu_365_p4;
wire   [0:0] icmp_ln428_fu_375_p2;
wire   [0:0] icmp_ln426_fu_343_p2;
wire   [0:0] icmp_ln427_fu_359_p2;
wire   [0:0] xor_ln426_fu_389_p2;
wire   [0:0] and_ln427_fu_395_p2;
wire   [1:0] shift_sel_fu_409_p6;
wire   [1:0] shift_sel_fu_409_p7;
wire   [1:0] shift_sel_fu_409_p8;
wire   [12:0] zext_ln440_fu_481_p1;
wire   [9:0] trunc_ln451_fu_532_p1;
wire   [10:0] grp_fu_540_p0;
wire   [9:0] grp_fu_540_p1;
wire   [19:0] grp_fu_540_p2;
wire    ap_CS_fsm_state7;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire   [20:0] grp_fu_540_p10;
wire  signed [1:0] shift_sel_fu_409_p1;
wire   [1:0] shift_sel_fu_409_p3;
wire   [1:0] shift_sel_fu_409_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start_reg = 1'b0;
#0 c_fu_136 = 4'd0;
end

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_src_id_start_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_src_id_start_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_src_id_start_address0),
    .ce0(CONNECTION_TABLE_src_id_start_ce0_local),
    .q0(CONNECTION_TABLE_src_id_start_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_weight_offset_ROM_AUTO_1R #(
    .DataWidth( 20 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_weight_offset_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_weight_offset_address0),
    .ce0(CONNECTION_TABLE_weight_offset_ce0_local),
    .q0(CONNECTION_TABLE_weight_offset_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_dst_size_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_dst_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_dst_size_address0),
    .ce0(CONNECTION_TABLE_dst_size_ce0_local),
    .q0(CONNECTION_TABLE_dst_size_q0)
);

snn_top_hls_process_pre_spike_aer_CONNECTION_TABLE_dst_id_start_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
CONNECTION_TABLE_dst_id_start_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONNECTION_TABLE_dst_id_start_address0),
    .ce0(CONNECTION_TABLE_dst_id_start_ce0_local),
    .q0(CONNECTION_TABLE_dst_id_start_q0)
);

snn_top_hls_apply_rstdp_reward_Pipeline_RSTDP_INNER grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start),
    .ap_done(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_done),
    .ap_idle(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_idle),
    .ap_ready(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_ready),
    .add_ln451(add_ln451_reg_691),
    .add_ln440_1(add_ln440_1_reg_661),
    .CONNECTION_TABLE_dst_id_start_load(CONNECTION_TABLE_dst_id_start_load_reg_632),
    .sext_ln485(pre_elig_reg_667),
    .shift_sel(shift_sel_reg_572),
    .sext_ln436(params_reward_scale_val),
    .empty_80(tmp_reg_567),
    .learn_weight_ready(learn_weight_ready),
    .pre_id(trunc_ln445_reg_651),
    .src_group(src_group_reg_681),
    .empty(tmp_35_reg_676),
    .post_eligibility_address0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_post_eligibility_address0),
    .post_eligibility_ce0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_post_eligibility_ce0),
    .post_eligibility_q0(post_eligibility_q0),
    .weight_memory_address0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_address0),
    .weight_memory_ce0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_ce0),
    .weight_memory_we0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_we0),
    .weight_memory_d0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_d0),
    .weight_memory_address1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_address1),
    .weight_memory_ce1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_ce1),
    .weight_memory_q1(weight_memory_q1),
    .learn_bridge_valid_i(learn_bridge_valid_i),
    .learn_bridge_valid_o(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o),
    .learn_bridge_valid_o_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o_ap_vld),
    .learn_bridge_group(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group),
    .learn_bridge_group_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group_ap_vld),
    .learn_bridge_src(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src),
    .learn_bridge_src_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src_ap_vld),
    .learn_bridge_dst(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst),
    .learn_bridge_dst_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_ap_vld),
    .learn_bridge_data(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data),
    .learn_bridge_data_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data_ap_vld),
    .learn_bridge_exc(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc),
    .learn_bridge_exc_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc_ap_vld),
    .learn_bridge_is_inter(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter),
    .learn_bridge_is_inter_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter_ap_vld),
    .learn_bridge_dst_group(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group),
    .learn_bridge_dst_group_ap_vld(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group_ap_vld)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_7_2_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 2 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 2 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
sparsemux_7_2_2_1_1_U153(
    .din0(2'd0),
    .din1(2'd1),
    .din2(shift_sel_fu_409_p6),
    .def(shift_sel_fu_409_p7),
    .sel(shift_sel_fu_409_p8),
    .dout(shift_sel_fu_409_p9)
);

snn_top_hls_mac_muladd_11ns_10ns_20ns_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 21 ))
mac_muladd_11ns_10ns_20ns_21_4_1_U154(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_540_p0),
    .din1(grp_fu_540_p1),
    .din2(grp_fu_540_p2),
    .ce(1'b1),
    .dout(grp_fu_540_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start_reg <= 1'b1;
        end else if ((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_ready == 1'b1)) begin
            grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln419_fu_305_p2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_fu_136 <= 4'd0;
    end else if (((icmp_ln440_fu_470_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        c_fu_136 <= add_ln436_reg_580;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ii_reg_252 <= 11'd0;
    end else if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
        ii_reg_252 <= add_ln440_reg_640;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        indvars_iv_reg_242 <= zext_ln448_1_fu_462_p1;
    end else if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
        indvars_iv_reg_242 <= add_ln440_1_reg_661;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        CONNECTION_TABLE_dst_id_start_load_reg_632 <= CONNECTION_TABLE_dst_id_start_q0;
        CONNECTION_TABLE_src_size_load_reg_610 <= CONNECTION_TABLE_src_size_q0;
        zext_ln448_1_reg_620[19 : 0] <= zext_ln448_1_fu_462_p1[19 : 0];
        zext_ln448_reg_615[11 : 0] <= zext_ln448_fu_458_p1[11 : 0];
        zext_ln455_reg_626[10 : 0] <= zext_ln455_fu_466_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln436_reg_580 <= add_ln436_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln440_1_reg_661 <= add_ln440_1_fu_503_p2;
        icmp_ln446_reg_672 <= icmp_ln446_fu_508_p2;
        pre_elig_reg_667 <= pre_eligibility_q0;
        src_group_reg_681 <= {{add_ln485_reg_645[10:7]}};
        tmp_35_reg_676 <= {{add_ln485_reg_645[12:11]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln440_reg_640 <= add_ln440_fu_475_p2;
        add_ln485_reg_645 <= add_ln485_fu_485_p2;
        trunc_ln445_reg_651 <= trunc_ln445_fu_490_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln451_reg_691 <= grp_fu_540_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln419_reg_556 <= and_ln419_fu_305_p2;
        shift_sel_reg_572 <= shift_sel_fu_409_p9;
        tmp_reg_567 <= reward_signal[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_data_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_dst_group_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_dst_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_exc_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_group_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_is_inter_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_src_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_valid_o_reg <= grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONNECTION_TABLE_dst_id_start_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_dst_id_start_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONNECTION_TABLE_dst_size_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_dst_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONNECTION_TABLE_src_id_start_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_src_id_start_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONNECTION_TABLE_src_size_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_src_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONNECTION_TABLE_weight_offset_ce0_local = 1'b1;
    end else begin
        CONNECTION_TABLE_weight_offset_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & ((icmp_ln436_fu_437_p2 == 1'd1) | (1'd0 == and_ln419_reg_556))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln436_fu_437_p2 == 1'd1) | (1'd0 == and_ln419_reg_556)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_data = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data;
    end else begin
        learn_bridge_data = learn_bridge_data_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_dst = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst;
    end else begin
        learn_bridge_dst = learn_bridge_dst_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_dst_group = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group;
    end else begin
        learn_bridge_dst_group = learn_bridge_dst_group_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_exc = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc;
    end else begin
        learn_bridge_exc = learn_bridge_exc_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_group = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group;
    end else begin
        learn_bridge_group = learn_bridge_group_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_is_inter = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter;
    end else begin
        learn_bridge_is_inter = learn_bridge_is_inter_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_src = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src;
    end else begin
        learn_bridge_src = learn_bridge_src_reg;
    end
end

always @ (*) begin
    if (((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln446_reg_672 == 1'd0))) begin
        learn_bridge_valid_o = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o;
    end else begin
        learn_bridge_valid_o = learn_bridge_valid_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pre_eligibility_ce0_local = 1'b1;
    end else begin
        pre_eligibility_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln436_fu_437_p2 == 1'd1) | (1'd0 == and_ln419_reg_556)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln440_fu_470_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln446_fu_508_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CONNECTION_TABLE_dst_id_start_address0 = zext_ln436_fu_449_p1;

assign CONNECTION_TABLE_dst_size_address0 = zext_ln436_fu_449_p1;

assign CONNECTION_TABLE_src_id_start_address0 = zext_ln436_fu_449_p1;

assign CONNECTION_TABLE_src_size_address0 = zext_ln436_fu_449_p1;

assign CONNECTION_TABLE_src_size_ce0 = CONNECTION_TABLE_src_size_ce0_local;

assign CONNECTION_TABLE_weight_offset_address0 = zext_ln436_fu_449_p1;

assign add_ln436_fu_443_p2 = (c_fu_136 + 4'd1);

assign add_ln440_1_fu_503_p2 = (zext_ln455_reg_626 + indvars_iv_reg_242);

assign add_ln440_fu_475_p2 = (ii_reg_252 + 11'd1);

assign add_ln485_fu_485_p2 = (zext_ln440_fu_481_p1 + zext_ln448_reg_615);

assign and_ln419_fu_305_p2 = (params_rstdp_enable_val & icmp_ln419_fu_299_p2);

assign and_ln427_fu_395_p2 = (xor_ln426_fu_389_p2 & icmp_ln427_fu_359_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_done == 1'b0) & (icmp_ln446_reg_672 == 1'd0));
end

assign grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_ap_start_reg;

assign grp_fu_540_p0 = zext_ln455_reg_626;

assign grp_fu_540_p1 = grp_fu_540_p10;

assign grp_fu_540_p10 = trunc_ln451_fu_532_p1;

assign grp_fu_540_p2 = zext_ln448_1_reg_620;

assign icmp_ln419_fu_299_p2 = ((reward_signal != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln426_fu_343_p2 = ((tmp_32_fu_333_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln427_fu_359_p2 = ((tmp_33_fu_349_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln428_fu_375_p2 = ((tmp_34_fu_365_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln436_fu_437_p2 = ((c_fu_136 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln440_fu_470_p2 = ((ii_reg_252 == CONNECTION_TABLE_src_size_load_reg_610) ? 1'b1 : 1'b0);

assign icmp_ln446_fu_508_p2 = ((pre_eligibility_q0 == 8'd0) ? 1'b1 : 1'b0);

assign learn_bridge_data_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_data_ap_vld;

assign learn_bridge_dst_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_ap_vld;

assign learn_bridge_dst_group_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_dst_group_ap_vld;

assign learn_bridge_exc_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_exc_ap_vld;

assign learn_bridge_group_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_group_ap_vld;

assign learn_bridge_is_inter_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_is_inter_ap_vld;

assign learn_bridge_src_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_src_ap_vld;

assign learn_bridge_valid_o_ap_vld = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_learn_bridge_valid_o_ap_vld;

assign post_eligibility_address0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_post_eligibility_address0;

assign post_eligibility_ce0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_post_eligibility_ce0;

assign pre_eligibility_address0 = zext_ln445_fu_494_p1;

assign pre_eligibility_ce0 = pre_eligibility_ce0_local;

assign reward_mag_1_fu_325_p3 = ((tmp_fu_311_p3[0:0] == 1'b1) ? reward_mag_fu_319_p2 : reward_signal);

assign reward_mag_fu_319_p2 = (8'd0 - reward_signal);

assign shift_sel_fu_409_p6 = ((icmp_ln428_fu_375_p2[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign shift_sel_fu_409_p7 = 'bx;

assign shift_sel_fu_409_p8 = {{icmp_ln426_fu_343_p2}, {and_ln427_fu_395_p2}};

assign tmp_32_fu_333_p4 = {{reward_mag_1_fu_325_p3[7:6]}};

assign tmp_33_fu_349_p4 = {{reward_mag_1_fu_325_p3[7:5]}};

assign tmp_34_fu_365_p4 = {{reward_mag_1_fu_325_p3[7:4]}};

assign tmp_fu_311_p3 = reward_signal[32'd7];

assign trunc_ln445_fu_490_p1 = add_ln485_fu_485_p2[6:0];

assign trunc_ln451_fu_532_p1 = ii_reg_252[9:0];

assign weight_memory_address0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_address0;

assign weight_memory_address1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_address1;

assign weight_memory_ce0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_ce0;

assign weight_memory_ce1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_ce1;

assign weight_memory_d0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_d0;

assign weight_memory_we0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_264_weight_memory_we0;

assign xor_ln426_fu_389_p2 = (icmp_ln426_fu_343_p2 ^ 1'd1);

assign zext_ln436_fu_449_p1 = c_fu_136;

assign zext_ln440_fu_481_p1 = ii_reg_252;

assign zext_ln445_fu_494_p1 = add_ln485_fu_485_p2;

assign zext_ln448_1_fu_462_p1 = CONNECTION_TABLE_weight_offset_q0;

assign zext_ln448_fu_458_p1 = CONNECTION_TABLE_src_id_start_q0;

assign zext_ln455_fu_466_p1 = CONNECTION_TABLE_dst_size_q0;

always @ (posedge ap_clk) begin
    zext_ln448_reg_615[12] <= 1'b0;
    zext_ln448_1_reg_620[20] <= 1'b0;
    zext_ln455_reg_626[20:11] <= 10'b0000000000;
end

endmodule //snn_top_hls_apply_rstdp_reward
