// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_apply_rstdp_reward_Pipeline_RSTDP_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add_ln451,
        add_ln440_1,
        CONNECTION_TABLE_dst_id_start_load,
        sext_ln485,
        shift_sel,
        sext_ln436,
        empty_80,
        learn_weight_ready,
        pre_id,
        src_group,
        empty,
        post_eligibility_address0,
        post_eligibility_ce0,
        post_eligibility_q0,
        weight_memory_address0,
        weight_memory_ce0,
        weight_memory_we0,
        weight_memory_d0,
        weight_memory_address1,
        weight_memory_ce1,
        weight_memory_q1,
        learn_bridge_valid_i,
        learn_bridge_valid_o,
        learn_bridge_valid_o_ap_vld,
        learn_bridge_group,
        learn_bridge_group_ap_vld,
        learn_bridge_src,
        learn_bridge_src_ap_vld,
        learn_bridge_dst,
        learn_bridge_dst_ap_vld,
        learn_bridge_data,
        learn_bridge_data_ap_vld,
        learn_bridge_exc,
        learn_bridge_exc_ap_vld,
        learn_bridge_is_inter,
        learn_bridge_is_inter_ap_vld,
        learn_bridge_dst_group,
        learn_bridge_dst_group_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [20:0] add_ln451;
input  [20:0] add_ln440_1;
input  [12:0] CONNECTION_TABLE_dst_id_start_load;
input  [7:0] sext_ln485;
input  [1:0] shift_sel;
input  [15:0] sext_ln436;
input  [0:0] empty_80;
input  [0:0] learn_weight_ready;
input  [6:0] pre_id;
input  [3:0] src_group;
input  [1:0] empty;
output  [12:0] post_eligibility_address0;
output   post_eligibility_ce0;
input  [7:0] post_eligibility_q0;
output  [19:0] weight_memory_address0;
output   weight_memory_ce0;
output   weight_memory_we0;
output  [3:0] weight_memory_d0;
output  [19:0] weight_memory_address1;
output   weight_memory_ce1;
input  [3:0] weight_memory_q1;
input  [0:0] learn_bridge_valid_i;
output  [0:0] learn_bridge_valid_o;
output   learn_bridge_valid_o_ap_vld;
output  [3:0] learn_bridge_group;
output   learn_bridge_group_ap_vld;
output  [6:0] learn_bridge_src;
output   learn_bridge_src_ap_vld;
output  [6:0] learn_bridge_dst;
output   learn_bridge_dst_ap_vld;
output  [3:0] learn_bridge_data;
output   learn_bridge_data_ap_vld;
output  [0:0] learn_bridge_exc;
output   learn_bridge_exc_ap_vld;
output  [0:0] learn_bridge_is_inter;
output   learn_bridge_is_inter_ap_vld;
output  [3:0] learn_bridge_dst_group;
output   learn_bridge_dst_group_ap_vld;

reg ap_idle;
reg[0:0] learn_bridge_valid_o;
reg learn_bridge_valid_o_ap_vld;
reg learn_bridge_group_ap_vld;
reg learn_bridge_src_ap_vld;
reg learn_bridge_dst_ap_vld;
reg learn_bridge_data_ap_vld;
reg learn_bridge_exc_ap_vld;
reg learn_bridge_is_inter_ap_vld;
reg learn_bridge_dst_group_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln451_fu_313_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [22:0] sext_ln436_cast_fu_289_p1;
reg  signed [22:0] sext_ln436_cast_reg_737;
wire  signed [15:0] sext_ln485_cast_fu_293_p1;
reg  signed [15:0] sext_ln485_cast_reg_742;
reg   [20:0] widx_2_reg_747;
wire   [12:0] post_id_fu_329_p2;
reg   [12:0] post_id_reg_756;
wire   [0:0] icmp_ln457_fu_360_p2;
reg   [0:0] icmp_ln457_reg_768;
reg   [0:0] icmp_ln457_reg_768_pp0_iter2_reg;
reg   [0:0] icmp_ln457_reg_768_pp0_iter3_reg;
reg   [0:0] icmp_ln457_reg_768_pp0_iter4_reg;
reg   [0:0] icmp_ln457_reg_768_pp0_iter5_reg;
reg   [0:0] icmp_ln457_reg_768_pp0_iter6_reg;
reg   [0:0] icmp_ln457_reg_768_pp0_iter7_reg;
reg   [19:0] weight_memory_addr_reg_777;
reg   [19:0] weight_memory_addr_reg_777_pp0_iter2_reg;
reg   [19:0] weight_memory_addr_reg_777_pp0_iter3_reg;
reg   [19:0] weight_memory_addr_reg_777_pp0_iter4_reg;
reg   [19:0] weight_memory_addr_reg_777_pp0_iter5_reg;
reg   [19:0] weight_memory_addr_reg_777_pp0_iter6_reg;
wire   [0:0] or_ln163_fu_385_p2;
reg   [0:0] or_ln163_reg_783;
reg   [0:0] or_ln163_reg_783_pp0_iter2_reg;
reg   [0:0] or_ln163_reg_783_pp0_iter3_reg;
reg   [0:0] or_ln163_reg_783_pp0_iter4_reg;
reg   [0:0] or_ln163_reg_783_pp0_iter5_reg;
reg   [0:0] or_ln163_reg_783_pp0_iter6_reg;
reg   [0:0] or_ln163_reg_783_pp0_iter7_reg;
wire   [0:0] icmp_ln168_fu_404_p2;
reg   [0:0] icmp_ln168_reg_787;
reg   [0:0] icmp_ln168_reg_787_pp0_iter2_reg;
reg   [0:0] icmp_ln168_reg_787_pp0_iter3_reg;
reg   [0:0] icmp_ln168_reg_787_pp0_iter4_reg;
reg   [0:0] icmp_ln168_reg_787_pp0_iter5_reg;
reg   [0:0] icmp_ln168_reg_787_pp0_iter6_reg;
reg   [0:0] icmp_ln168_reg_787_pp0_iter7_reg;
wire   [6:0] base_scaled_4_fu_538_p11;
reg  signed [6:0] base_scaled_4_reg_791;
wire  signed [15:0] sext_ln475_fu_580_p1;
reg  signed [15:0] sext_ln475_reg_801;
wire   [15:0] delta_fu_584_p2;
reg   [15:0] delta_reg_806;
reg  signed [3:0] current_w_reg_811;
wire   [3:0] updated_fu_644_p3;
reg   [3:0] updated_reg_816;
wire   [63:0] zext_ln456_fu_335_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln451_fu_356_p1;
wire   [3:0] dst_group_fu_410_p4;
reg   [10:0] jj_fu_186;
wire   [10:0] add_ln451_1_fu_319_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_jj_2;
reg   [20:0] widx_fu_190;
wire   [20:0] add_ln492_fu_340_p2;
reg   [20:0] ap_sig_allocacmp_widx_2;
reg    post_eligibility_ce0_local;
reg    weight_memory_ce1_local;
reg    weight_memory_we0_local;
reg    weight_memory_ce0_local;
wire   [12:0] zext_ln451_1_fu_325_p1;
wire  signed [7:0] icmp_ln457_fu_360_p0;
wire  signed [7:0] sext_ln459_fu_366_p0;
wire  signed [7:0] grp_fu_370_p1;
wire   [0:0] xor_ln163_fu_379_p2;
wire   [1:0] tmp_30_fu_390_p4;
wire   [1:0] or_ln168_fu_399_p2;
wire   [15:0] grp_fu_370_p2;
wire   [3:0] base_scaled_fu_461_p4;
wire   [5:0] base_scaled_2_fu_485_p4;
wire   [4:0] base_scaled_3_fu_499_p4;
wire   [0:0] icmp_ln465_fu_513_p2;
wire   [0:0] icmp_ln465_1_fu_518_p2;
wire   [0:0] icmp_ln465_2_fu_523_p2;
wire  signed [6:0] base_scaled_4_fu_538_p2;
wire  signed [6:0] base_scaled_4_fu_538_p4;
wire   [6:0] base_scaled_4_fu_538_p6;
wire  signed [6:0] base_scaled_4_fu_538_p8;
wire   [6:0] base_scaled_4_fu_538_p9;
wire   [2:0] base_scaled_4_fu_538_p10;
wire  signed [15:0] grp_fu_565_p1;
wire   [22:0] grp_fu_565_p2;
wire   [14:0] scaled_fu_570_p4;
wire   [15:0] delta_1_fu_590_p3;
wire  signed [15:0] sext_ln482_fu_595_p1;
wire   [15:0] w_fu_598_p2;
wire   [12:0] tmp_29_fu_604_p4;
wire   [0:0] icmp_ln131_fu_614_p2;
wire   [0:0] icmp_ln132_fu_620_p2;
wire   [0:0] or_ln131_fu_638_p2;
wire   [3:0] select_ln131_fu_630_p3;
wire   [3:0] trunc_ln133_fu_626_p1;
wire   [0:0] tmp_31_fu_653_p3;
wire   [3:0] mag_5_fu_666_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [2:0] base_scaled_4_fu_538_p1;
wire   [2:0] base_scaled_4_fu_538_p3;
wire   [2:0] base_scaled_4_fu_538_p5;
wire   [2:0] base_scaled_4_fu_538_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 jj_fu_186 = 11'd0;
#0 widx_fu_190 = 21'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_mul_8s_8s_16_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_3_1_U126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln459_fu_366_p0),
    .din1(grp_fu_370_p1),
    .ce(1'b1),
    .dout(grp_fu_370_p2)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_9_3_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 7 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 7 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 7 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
sparsemux_9_3_7_1_1_U127(
    .din0(base_scaled_4_fu_538_p2),
    .din1(base_scaled_4_fu_538_p4),
    .din2(base_scaled_4_fu_538_p6),
    .din3(base_scaled_4_fu_538_p8),
    .def(base_scaled_4_fu_538_p9),
    .sel(base_scaled_4_fu_538_p10),
    .dout(base_scaled_4_fu_538_p11)
);

snn_top_hls_mul_7s_16s_23_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 23 ))
mul_7s_16s_23_3_1_U128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(base_scaled_4_reg_791),
    .din1(grp_fu_565_p1),
    .ce(1'b1),
    .dout(grp_fu_565_p2)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln451_fu_313_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            jj_fu_186 <= add_ln451_1_fu_319_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            jj_fu_186 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln451_fu_313_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            widx_fu_190 <= add_ln492_fu_340_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            widx_fu_190 <= add_ln451;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln168_reg_787 <= icmp_ln168_fu_404_p2;
        icmp_ln457_reg_768 <= icmp_ln457_fu_360_p2;
        or_ln163_reg_783 <= or_ln163_fu_385_p2;
        post_id_reg_756 <= post_id_fu_329_p2;
        sext_ln436_cast_reg_737 <= sext_ln436_cast_fu_289_p1;
        sext_ln485_cast_reg_742 <= sext_ln485_cast_fu_293_p1;
        weight_memory_addr_reg_777 <= zext_ln451_fu_356_p1;
        widx_2_reg_747 <= ap_sig_allocacmp_widx_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        base_scaled_4_reg_791 <= base_scaled_4_fu_538_p11;
        delta_reg_806 <= delta_fu_584_p2;
        icmp_ln168_reg_787_pp0_iter2_reg <= icmp_ln168_reg_787;
        icmp_ln168_reg_787_pp0_iter3_reg <= icmp_ln168_reg_787_pp0_iter2_reg;
        icmp_ln168_reg_787_pp0_iter4_reg <= icmp_ln168_reg_787_pp0_iter3_reg;
        icmp_ln168_reg_787_pp0_iter5_reg <= icmp_ln168_reg_787_pp0_iter4_reg;
        icmp_ln168_reg_787_pp0_iter6_reg <= icmp_ln168_reg_787_pp0_iter5_reg;
        icmp_ln168_reg_787_pp0_iter7_reg <= icmp_ln168_reg_787_pp0_iter6_reg;
        icmp_ln457_reg_768_pp0_iter2_reg <= icmp_ln457_reg_768;
        icmp_ln457_reg_768_pp0_iter3_reg <= icmp_ln457_reg_768_pp0_iter2_reg;
        icmp_ln457_reg_768_pp0_iter4_reg <= icmp_ln457_reg_768_pp0_iter3_reg;
        icmp_ln457_reg_768_pp0_iter5_reg <= icmp_ln457_reg_768_pp0_iter4_reg;
        icmp_ln457_reg_768_pp0_iter6_reg <= icmp_ln457_reg_768_pp0_iter5_reg;
        icmp_ln457_reg_768_pp0_iter7_reg <= icmp_ln457_reg_768_pp0_iter6_reg;
        or_ln163_reg_783_pp0_iter2_reg <= or_ln163_reg_783;
        or_ln163_reg_783_pp0_iter3_reg <= or_ln163_reg_783_pp0_iter2_reg;
        or_ln163_reg_783_pp0_iter4_reg <= or_ln163_reg_783_pp0_iter3_reg;
        or_ln163_reg_783_pp0_iter5_reg <= or_ln163_reg_783_pp0_iter4_reg;
        or_ln163_reg_783_pp0_iter6_reg <= or_ln163_reg_783_pp0_iter5_reg;
        or_ln163_reg_783_pp0_iter7_reg <= or_ln163_reg_783_pp0_iter6_reg;
        sext_ln475_reg_801 <= sext_ln475_fu_580_p1;
        updated_reg_816 <= updated_fu_644_p3;
        weight_memory_addr_reg_777_pp0_iter2_reg <= weight_memory_addr_reg_777;
        weight_memory_addr_reg_777_pp0_iter3_reg <= weight_memory_addr_reg_777_pp0_iter2_reg;
        weight_memory_addr_reg_777_pp0_iter4_reg <= weight_memory_addr_reg_777_pp0_iter3_reg;
        weight_memory_addr_reg_777_pp0_iter5_reg <= weight_memory_addr_reg_777_pp0_iter4_reg;
        weight_memory_addr_reg_777_pp0_iter6_reg <= weight_memory_addr_reg_777_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        current_w_reg_811 <= weight_memory_q1;
    end
end

always @ (*) begin
    if (((icmp_ln451_fu_313_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_jj_2 = 11'd0;
    end else begin
        ap_sig_allocacmp_jj_2 = jj_fu_186;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_widx_2 = add_ln451;
    end else begin
        ap_sig_allocacmp_widx_2 = widx_fu_190;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln168_reg_787_pp0_iter7_reg == 1'd1) & (or_ln163_reg_783_pp0_iter7_reg == 1'd1) & (icmp_ln457_reg_768_pp0_iter7_reg == 1'd0))) begin
        learn_bridge_data_ap_vld = 1'b1;
    end else begin
        learn_bridge_data_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_dst_ap_vld = 1'b1;
    end else begin
        learn_bridge_dst_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_dst_group_ap_vld = 1'b1;
    end else begin
        learn_bridge_dst_group_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln168_reg_787_pp0_iter7_reg == 1'd1) & (or_ln163_reg_783_pp0_iter7_reg == 1'd1) & (icmp_ln457_reg_768_pp0_iter7_reg == 1'd0))) begin
        learn_bridge_exc_ap_vld = 1'b1;
    end else begin
        learn_bridge_exc_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_group_ap_vld = 1'b1;
    end else begin
        learn_bridge_group_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_is_inter_ap_vld = 1'b1;
    end else begin
        learn_bridge_is_inter_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_src_ap_vld = 1'b1;
    end else begin
        learn_bridge_src_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_valid_o = 1'd1;
    end else begin
        learn_bridge_valid_o = learn_bridge_valid_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln168_fu_404_p2 == 1'd1) & (or_ln163_fu_385_p2 == 1'd1) & (icmp_ln457_fu_360_p2 == 1'd0))) begin
        learn_bridge_valid_o_ap_vld = 1'b1;
    end else begin
        learn_bridge_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        post_eligibility_ce0_local = 1'b1;
    end else begin
        post_eligibility_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1)))) begin
        weight_memory_ce0_local = 1'b1;
    end else begin
        weight_memory_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        weight_memory_ce1_local = 1'b1;
    end else begin
        weight_memory_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln457_reg_768_pp0_iter6_reg == 1'd0))) begin
        weight_memory_we0_local = 1'b1;
    end else begin
        weight_memory_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln451_1_fu_319_p2 = (ap_sig_allocacmp_jj_2 + 11'd1);

assign add_ln492_fu_340_p2 = (ap_sig_allocacmp_widx_2 + 21'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign base_scaled_2_fu_485_p4 = {{grp_fu_370_p2[15:10]}};

assign base_scaled_3_fu_499_p4 = {{grp_fu_370_p2[15:11]}};

assign base_scaled_4_fu_538_p10 = {{{icmp_ln465_fu_513_p2}, {icmp_ln465_1_fu_518_p2}}, {icmp_ln465_2_fu_523_p2}};

assign base_scaled_4_fu_538_p2 = $signed(base_scaled_3_fu_499_p4);

assign base_scaled_4_fu_538_p4 = $signed(base_scaled_2_fu_485_p4);

assign base_scaled_4_fu_538_p6 = {{grp_fu_370_p2[15:9]}};

assign base_scaled_4_fu_538_p8 = $signed(base_scaled_fu_461_p4);

assign base_scaled_4_fu_538_p9 = 'bx;

assign base_scaled_fu_461_p4 = {{grp_fu_370_p2[15:12]}};

assign delta_1_fu_590_p3 = ((empty_80[0:0] == 1'b1) ? delta_reg_806 : sext_ln475_reg_801);

assign delta_fu_584_p2 = ($signed(16'd0) - $signed(sext_ln475_fu_580_p1));

assign dst_group_fu_410_p4 = {{post_id_reg_756[10:7]}};

assign grp_fu_370_p1 = sext_ln485_cast_reg_742;

assign grp_fu_565_p1 = sext_ln436_cast_reg_737;

assign icmp_ln131_fu_614_p2 = (($signed(tmp_29_fu_604_p4) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_620_p2 = (($signed(w_fu_598_p2) < $signed(16'd65528)) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_404_p2 = ((or_ln168_fu_399_p2 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln451_fu_313_p2 = ((ap_sig_allocacmp_widx_2 == add_ln440_1) ? 1'b1 : 1'b0);

assign icmp_ln457_fu_360_p0 = post_eligibility_q0;

assign icmp_ln457_fu_360_p2 = ((icmp_ln457_fu_360_p0 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln465_1_fu_518_p2 = ((shift_sel == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln465_2_fu_523_p2 = ((shift_sel == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln465_fu_513_p2 = ((shift_sel == 2'd2) ? 1'b1 : 1'b0);

assign learn_bridge_data = ((tmp_31_fu_653_p3[0:0] == 1'b1) ? mag_5_fu_666_p2 : updated_reg_816);

assign learn_bridge_dst = post_id_reg_756[6:0];

assign learn_bridge_dst_group = {{post_id_reg_756[10:7]}};

assign learn_bridge_exc = (tmp_31_fu_653_p3 ^ 1'd1);

assign learn_bridge_group = src_group;

assign learn_bridge_is_inter = ((src_group != dst_group_fu_410_p4) ? 1'b1 : 1'b0);

assign learn_bridge_src = pre_id;

assign mag_5_fu_666_p2 = (4'd0 - updated_reg_816);

assign or_ln131_fu_638_p2 = (icmp_ln132_fu_620_p2 | icmp_ln131_fu_614_p2);

assign or_ln163_fu_385_p2 = (xor_ln163_fu_379_p2 | learn_weight_ready);

assign or_ln168_fu_399_p2 = (tmp_30_fu_390_p4 | empty);

assign post_eligibility_address0 = zext_ln456_fu_335_p1;

assign post_eligibility_ce0 = post_eligibility_ce0_local;

assign post_id_fu_329_p2 = (zext_ln451_1_fu_325_p1 + CONNECTION_TABLE_dst_id_start_load);

assign scaled_fu_570_p4 = {{grp_fu_565_p2[22:8]}};

assign select_ln131_fu_630_p3 = ((icmp_ln131_fu_614_p2[0:0] == 1'b1) ? 4'd7 : 4'd8);

assign sext_ln436_cast_fu_289_p1 = $signed(sext_ln436);

assign sext_ln459_fu_366_p0 = post_eligibility_q0;

assign sext_ln475_fu_580_p1 = $signed(scaled_fu_570_p4);

assign sext_ln482_fu_595_p1 = current_w_reg_811;

assign sext_ln485_cast_fu_293_p1 = $signed(sext_ln485);

assign tmp_29_fu_604_p4 = {{w_fu_598_p2[15:3]}};

assign tmp_30_fu_390_p4 = {{post_id_reg_756[12:11]}};

assign tmp_31_fu_653_p3 = updated_reg_816[32'd3];

assign trunc_ln133_fu_626_p1 = w_fu_598_p2[3:0];

assign updated_fu_644_p3 = ((or_ln131_fu_638_p2[0:0] == 1'b1) ? select_ln131_fu_630_p3 : trunc_ln133_fu_626_p1);

assign w_fu_598_p2 = ($signed(delta_1_fu_590_p3) + $signed(sext_ln482_fu_595_p1));

assign weight_memory_address0 = weight_memory_addr_reg_777_pp0_iter6_reg;

assign weight_memory_address1 = weight_memory_addr_reg_777_pp0_iter2_reg;

assign weight_memory_ce0 = weight_memory_ce0_local;

assign weight_memory_ce1 = weight_memory_ce1_local;

assign weight_memory_d0 = updated_fu_644_p3;

assign weight_memory_we0 = weight_memory_we0_local;

assign xor_ln163_fu_379_p2 = (learn_bridge_valid_i ^ 1'd1);

assign zext_ln451_1_fu_325_p1 = ap_sig_allocacmp_jj_2;

assign zext_ln451_fu_356_p1 = widx_2_reg_747;

assign zext_ln456_fu_335_p1 = post_id_fu_329_p2;

endmodule //snn_top_hls_apply_rstdp_reward_Pipeline_RSTDP_INNER
